"""E27 SEED REPLICATES OF THE TWO RECOMMENDATION ARMS (reviewer-2 finding R4:
every frontier number in this program rests on ONE seed and ONE data order;
the retrain-recommendation rule in BRAINSTORM_STATE demands 2-3 seeds before an
architecture can enter the recommendation).

TWO ARMS, each an exact replicate of a stored arm with the INIT SEED changed
and NOTHING else:
  E27a  frontier arm -- the bandwidth-reinvestment architecture at the
        readability dial (in-loss group-lasso 1e-4): qk_e15_reinvest_run.
        make_e15c(s=15) verbatim, trained through the qk_e19_dial_run trainer
        expression. Seed-0 twin: qk_e19_a (fresh held CE 4.9742, plain
        Spearman 0.7911, covariance-composed 0.8259).
  E27b  readable-recipe arm -- per-slot RMSNorm + Muon + in-loss group-lasso
        3e-5: qk_e7_evenout_run.make_e7m1 verbatim through the
        qk_e9_compose_run.muon_lasso_trainer expression. Seed-0 twin:
        qk_e9_a (fresh held CE 5.0547, plain Spearman 0.7711,
        covariance-composed 0.8575).

WHAT VARIES, EXACTLY ONE THING. Q.SEED (0 -> 1) is consumed ONLY by the model
factories (`torch.manual_seed(Q.SEED)` immediately before construction). The
DATA ORDER is generated by Q.epoch_order(epoch) from the SEPARATE, UNCHANGED
Q.DATA_SEED = 1234, so both replicates see the identical 132,000-row single-
epoch stream in the identical order as their seed-0 twins. This is deliberate:
holding data order fixed makes the measured delta a pure INIT-SENSITIVITY
number, not a joint init+order number. A data-order replicate is a separate
experiment (the standing logging list asks for one) and is NOT what this run
measures -- do not read these deltas as full run-to-run spread.

POSITIVE CONTROLS, BEFORE TRAINING:
  1. CONFIG EQUALITY: the training configuration this runner is about to use
     (lr, group_coeff, width, batch, steps, epochs, corpus, held_fresh,
     adamw lr) must equal the stored parent JSON record field for field. Any
     difference other than the seed aborts the run.
  2. SEED-0 REPRODUCTION: 3 steps through THIS runner's exact training call at
     Q.SEED = 0 must reproduce the stored parent's step-0 training CE exactly
     (the parents log round(ce, 4) at step 0). Proves the replication path is
     the parent's path, so any later difference is attributable to the seed.
  3. SEED ACTUALLY CHANGED: the same 3 steps at Q.SEED = 1 must give a
     DIFFERENT step-0 CE (guards the silent no-op where the factory ignores
     the seed).
  4. AFTER TRAINING: the saved checkpoint config dict must equal the parent
     checkpoint's config dict on every key except SEED (parent 0, replicate 1).

MEASURES (full standard set, per arm): fresh single-epoch training curve every
200 steps + held-100 curve; final fresh held CE; per-sequence heldloss.npy;
old-cooc held record; paired deltas vs the seed-0 twin AND vs the E0a/E0b
controls with sequence-clustered SEs; the generalized variable-slot-dim light
probe (qk_e18 gate-1 validated: reproduces weight_support exactly at uniform
11) giving PLAIN wiring Spearman, and the covariance-composed re-scoring
(qk_e18 gate-2 validated) giving the standard reported metric; wiring-
trajectory npz every 200 steps (harness standing upgrade).

REGISTERED PREDICTIONS (merged before training):
  CE seed spread <= 0.02 nats on both arms.
  Spearman seed spread UNKNOWN -- measuring it IS the point of this run. If
  either metric's spread exceeds 0.08 (the R1 sampling SE, i.e. the size of a
  "tie" on this metric), the frontier's readability axis is seed-dominated and
  every readability comparison in the program needs 3+ seeds; the JSON states
  that consequence explicitly.

Idempotent on qk_e27.json keys and checkpoints; smoke-gated via QK_SMOKE=1."""
import os
os.environ.setdefault('PYTORCH_CUDA_ALLOC_CONF', 'expandable_segments:True')
import json

import numpy as np

import qk_e_common as E
from qk_e_common import Q, C, DEPTH, torch
import qk_e7_evenout_run as E7R
import qk_e9_compose_run as E9R            # muon_lasso_trainer (recipe arm)
import qk_e15_reinvest_run as E15R         # E15cRoute + make_e15c + solve_slot_c
import qk_e19_dial_run as E19R             # trainer (frontier arm) + dial
import qk_e18_probe_upgrades as E18U       # generalized + cov-composed probes
import qk_e17_composed_wiring as E17
import qk_deeproute_train_2 as R2

# E17/E18 set E.DEV='cpu' for their weight-only use -- restore the convention.
E.DEV = 'cpu' if E.SMOKE else 'cuda'

JP = E.jpath('qk_e27.json')
SEED0 = Q.SEED                             # 0, the stored arms' seed
SEED1 = Q.SEED + 1                         # the replicate seed
GATE_TOL = 1e-3
R1_SE = 0.08                               # reviewer-2 R1 Spearman sampling SE
CE_PRED = 0.02
NG = E.NGROUP

# fields of the stored parent JSON record that MUST match exactly (control 1)
CFG_FIELDS = ('lr', 'group_coeff', 'width', 'batch', 'steps', 'epochs',
              'corpus', 'held_fresh')


def set_seed(s):
    """Q.SEED is read ONLY by the model factories; the data order comes from
    the untouched Q.DATA_SEED. Setting it globally also stamps the correct
    seed into the checkpoint config dict written by E.train_muon."""
    Q.SEED = s


# ---------------- arms ------------------------------------------------------
def arms(s_c):
    return (
        {'tag': 'E27a_frontier', 'stem': 'qk_e27_frontier_s1',
         'parent_stem': 'qk_e19_a', 'parent_json': 'qk_e19.json',
         'parent_key': 'E19a', 'parent_lp': 'light_probe_E19a_var_dims',
         'parent_cw': 'composed_wiring_E19a',
         'gc': E19R.GC19, 'dims': [s_c] * NG,
         'factory': (lambda: E15R.make_e15c(s=s_c)),
         'trainer': E19R.trainer,
         'design': 'E15c bandwidth-reinvestment architecture with the '
                   'readability dial: in-loss group-lasso 1e-4 (verbatim '
                   'qk_e19_dial_run arm E19a) at seed 1',
         'slot': s_c},
        {'tag': 'E27b_recipe', 'stem': 'qk_e27_recipe_s1',
         'parent_stem': 'qk_e9_a', 'parent_json': 'qk_e9.json',
         'parent_key': 'E9a', 'parent_lp': 'light_probe_E9a',
         'parent_cw': None,
         'gc': E9R.GC9, 'dims': [E.SUB] * NG,
         'factory': E7R.make_e7m1,
         'trainer': E9R.muon_lasso_trainer,
         'design': 'readable recipe: per-slot RMSNorm + Muon + in-loss '
                   'group-lasso 3e-5 (verbatim qk_e9_compose_run arm E9a) '
                   'at seed 1',
         'slot': E.SUB},
    )


def parent_rec(a):
    return E.loadj(E.jpath(a['parent_json']))[a['parent_key']]


# ---------------- control 1: config equality --------------------------------
def control_config_equality(a, mlr):
    key = f"control_config_equality_{a['tag']}"
    if E.SMOKE or E.loadj(JP).get(key, {}).get('pass'):
        return
    p = parent_rec(a)
    mine = {'lr': mlr, 'group_coeff': a['gc'], 'width': Q.D,
            'batch': Q.BATCH, 'steps': E.V8T.STEPS, 'epochs': 1,
            'corpus': f'corpus_fresh shards prefix [{E.V8T.STEPS * Q.BATCH}], '
                      'single pass',
            'held_fresh': 'corpus_fresh/fresh34k.npy rows [33000:34500] '
                          '(pure eval corpus)'}
    diffs = {f: [p.get(f), mine[f]] for f in CFG_FIELDS if p.get(f) != mine[f]}
    rec = {'parent': a['parent_key'], 'parent_json': a['parent_json'],
           'fields_checked': list(CFG_FIELDS),
           'stored_parent_config': {f: p.get(f) for f in CFG_FIELDS},
           'this_run_config': mine,
           'mismatches': diffs,
           'adamw_lr_this_run': E.get_lr(),
           'stored_parent_adamw_lr': p.get('lr_adamw_for_embedding'),
           'seed_parent': SEED0, 'seed_this_run': SEED1,
           'data_seed_both': Q.DATA_SEED,
           'note': 'the ONLY intended difference is the init seed; the data '
                   'order comes from Q.DATA_SEED which is unchanged',
           'pass': bool(not diffs)}
    E.merge(JP, key, rec)
    print(f"{key}: {len(diffs)} mismatches -> "
          f"{'PASS' if rec['pass'] else 'FAIL'} {diffs}", flush=True)
    assert rec['pass'], f'{key} FAILED: {diffs}'


# ---------------- controls 2+3: seed-0 reproduction / seed changed ----------
def three_step(a, mlr, seed):
    set_seed(seed)
    try:
        log = a['trainer'](mlr, a['gc'], 3, log_every=1, save=False,
                           factory=a['factory'])
    finally:
        set_seed(SEED0)
    return [x[1] for x in log['train_loss']], log['final_held_ce']


def control_seed_gate(a, mlr):
    key = f"control_seed_gate_{a['tag']}"
    if E.SMOKE or E.loadj(JP).get(key, {}).get('pass'):
        return
    p = parent_rec(a)
    stored0 = p['train_curve_every200'][0]           # [step, ce, ema] at 0
    assert stored0[0] == 0, stored0
    ce0, held0 = three_step(a, mlr, SEED0)
    ce1, held1 = three_step(a, mlr, SEED1)
    d_repro = abs(round(ce0[0], 4) - stored0[1])
    d_seed = abs(ce1[0] - ce0[0])
    rec = {'stored_parent_step0_ce': stored0[1],
           'rerun_seed0_per_step_ce': ce0,
           'rerun_seed1_per_step_ce': ce1,
           'seed0_step0_abs_diff_vs_stored': d_repro,
           'seed1_vs_seed0_step0_abs_diff': d_seed,
           'rerun_seed0_held100': held0, 'rerun_seed1_held100': held1,
           'note': 'control 2 (reproduction: the stored parent logs step-0 CE '
                   'at 4 dp, so agreement must be at that resolution -- step-0 '
                   'CE depends only on the init and the first batch, neither '
                   'of which this runner changes at seed 0) + control 3 (the '
                   'seed actually moves the init)',
           'repro_tol': 1e-4,
           'pass': bool(d_repro <= 1e-4 and d_seed > 1e-4)}
    E.merge(JP, key, rec)
    print(f"{key}: seed0 step0 {ce0[0]:.4f} vs stored {stored0[1]} "
          f"(diff {d_repro:.1e}); seed1 step0 {ce1[0]:.4f} "
          f"(moved {d_seed:.3e}) -> {'PASS' if rec['pass'] else 'FAIL'}",
          flush=True)
    assert rec['pass'], f'{key} FAILED'


# ---------------- control 4: checkpoint config-dict equality ----------------
def control_ckpt_config(a):
    key = f"control_ckpt_config_{a['tag']}"
    if E.SMOKE or E.loadj(JP).get(key, {}).get('pass'):
        return
    if not (os.path.exists(E.ckpath(a['stem']))
            and os.path.exists(E.ckpath(a['parent_stem']))):
        return
    cn = torch.load(E.ckpath(a['stem']), map_location='cpu',
                    weights_only=False)['config']
    cp = torch.load(E.ckpath(a['parent_stem']), map_location='cpu',
                    weights_only=False)['config']
    keys = sorted(set(cn) | set(cp))
    diffs = {k: [cp.get(k), cn.get(k)] for k in keys if cp.get(k) != cn.get(k)}
    rec = {'parent_checkpoint': f"{a['parent_stem']}.pt",
           'replicate_checkpoint': f"{a['stem']}.pt",
           'parent_config': {k: cp.get(k) for k in keys},
           'replicate_config': {k: cn.get(k) for k in keys},
           'differing_keys': sorted(diffs),
           'differences': diffs,
           'pass': bool(sorted(diffs) == ['SEED']
                        and cp.get('SEED') == SEED0
                        and cn.get('SEED') == SEED1)}
    E.merge(JP, key, rec)
    print(f"{key}: differing keys {sorted(diffs)} -> "
          f"{'PASS' if rec['pass'] else 'FAIL'}", flush=True)
    assert rec['pass'], f'{key} FAILED: {diffs}'


# ---------------- probes ----------------------------------------------------
def probe(a):
    """Generalized variable-slot-dim light probe (plain Spearman) + the
    covariance-composed re-scoring (the standard reported metric). Same code
    path for both arms; qk_e18 gate 1 proved it reproduces weight_support
    exactly at uniform 11, gate 2 that the composition reproduces E17."""
    stem, dims = a['stem'], a['dims']
    if E.SMOKE or not os.path.exists(E.ckpath(stem)):
        return
    lp_key, cw_key = f"light_probe_{a['tag']}", f"composed_wiring_{a['tag']}"
    if lp_key not in E.loadj(JP):
        print(f"{a['tag']} light probe (dims {dims[0]} x {NG}) ...",
              flush=True)
        m, _ = E.load_arm(stem, a['factory'])
        Ws = m.wte.weight.shape[1]
        assert Ws == sum(dims), (Ws, sum(dims))
        base, dce = E18U.gen_consumption(m, Ws)
        wp = E18U.wpairs(m, dims)
        sup = E18U.score(E18U.gen_gram_table(m, dims), wp)
        cau = [dce[li][si] for li, si in wp]
        eff = [k for k in range(len(wp)) if cau[k] > C.EFFECTUAL]
        agr = E17.agreement(sup, cau, eff)
        # probe-equivalence gate on THIS checkpoint (qk_e18 gate 1, re-run on
        # the replicate): at uniform slot width the generalized scorer must
        # reproduce E.weight_support, the scorer that produced the parent's
        # stored number -- so the delta below is a seed delta, not a probe
        # delta.
        rel = None
        if all(d == E.SUB for d in dims):
            ws = E.weight_support(m)
            rel = max(abs(sup[i] - ws[li][si]) / max(abs(ws[li][si]), 1e-12)
                      for i, (li, si) in enumerate(wp))
            print(f"{a['tag']} probe equivalence vs weight_support: max rel "
                  f"{rel:.2e}", flush=True)
            assert rel < 1e-6, f'probe equivalence FAILED ({rel})'
        totals = {str(j): round(sum(dce[li].get(si, 0.0) for li in dce
                                    for si in (1 + 2 * j, 2 + 2 * j)
                                    if si in dce[li]), 5)
                  for j in range(DEPTH)}
        srt = sorted([(li, si, dce[li][si]) for li in dce for si in dce[li]],
                     key=lambda p: -p[2])
        E.merge(JP, lp_key, {
            'checkpoint': f'{stem}.pt', 'seed': SEED1, 'slot_dims': dims,
            'stream_width': Ws, 'compute_width': Q.D,
            'base_ce_fp32_abl_oldheld': round(base, 5),
            'wiring_n_pairs': len(wp),
            'wiring_spearman_all': agr['spearman_all'],
            'wiring_n_effectual': len(eff),
            'wiring_spearman_effectual': agr['spearman_effectual'],
            'wiring_top10_precision': agr['top10_precision'],
            'per_block_total_consumption': totals,
            'dead_blocks_below_0.001': [b for b in totals if totals[b] < 0.001],
            'consumption_top20': [
                {'consumer': ('readout' if li == DEPTH else f'block{li}'),
                 'source': R2.stream_name(si), 'dce': round(v, 5)}
                for li, si, v in srt[:20]],
            'consumption_matrix': {str(li): {str(si): round(v, 6)
                                             for si, v in dce[li].items()}
                                   for li in dce},
            'weight_support_matrix': {
                str(li): {str(si): round(sup[i], 3)
                          for i, (l2, si) in enumerate(wp) if l2 == li}
                for li in range(DEPTH + 1)},
            'probe_equivalence_vs_weight_support_max_rel': rel,
            'note': 'generalized variable-slot-dim probe (qk_e18 gate 1); '
                    'causal = mean-ablation on old cooc held [:96], fp32 -- '
                    'identical machinery to R2.consumption_graph (same '
                    'OLD_HELD tensor, same ABL_N 96)'})
        print(f"{a['tag']} plain wiring Spearman {agr['spearman_all']} "
              f"effectual({len(eff)}) {agr['spearman_effectual']}", flush=True)
        del m
        torch.cuda.empty_cache()
    if cw_key not in E.loadj(JP):
        lp = E.loadj(JP)[lp_key]
        print(f"{a['tag']} covariance-composed re-scoring ...", flush=True)
        m, _ = E.load_arm(stem, a['factory'])
        wp = E18U.wpairs(m, dims)
        cau = E18U.stored_cau(lp, wp)
        tables, meta, _ = E18U.composed_tables(m, dims, cau, wp, E.DEV,
                                               remnant=False)
        chk = abs(tables['plain']['spearman_all'] - lp['wiring_spearman_all'])
        assert chk <= GATE_TOL, f'plain does not reproduce the probe ({chk})'
        rec = {'checkpoint': f'{stem}.pt', 'seed': SEED1,
               'slot_dims_uniform': dims[0],
               'plain_reproduction_abs_diff': round(chk, 6),
               'tables': tables}
        rec.update(meta)
        E.merge(JP, cw_key, rec)
        print(f"{a['tag']} plain {tables['plain']['spearman_all']} -> cov "
              f"{tables['cov_composed']['spearman_all']}", flush=True)
        del m
        torch.cuda.empty_cache()


# ---------------- summary ---------------------------------------------------
def parent_spearmans(a):
    if E.SMOKE:
        return None, None
    pj = E.loadj(E.jpath(a['parent_json']))
    plain = pj[a['parent_lp']]['wiring_spearman_all']
    if a['parent_cw']:
        cov = pj[a['parent_cw']]['tables']['cov_composed']['spearman_all']
    else:                                     # E9a's composition lives in E17
        cov = E.loadj(E.jpath('qk_e17.json'))[
            'tables']['cov_composed']['spearman_all']
    return plain, cov


def summarize(all_arms):
    j = E.loadj(JP)
    rows, spreads_ce, spreads_sp = {}, [], []
    for a in all_arms:
        if a['tag'] not in j:
            continue
        p = {} if E.SMOKE else parent_rec(a)
        row = {'parent': a['parent_key'],
               'seed': SEED1, 'parent_seed': SEED0,
               'ce_replicate': j[a['tag']]['final_held_ce_fresh_bf16'],
               'ce_parent': p.get('final_held_ce_fresh_bf16'),
               'diverged': j[a['tag']]['diverged']}
        if row['ce_replicate'] is not None and row['ce_parent'] is not None:
            row['delta_ce'] = round(row['ce_replicate'] - row['ce_parent'], 5)
            spreads_ce.append(abs(row['delta_ce']))
        pr = j.get(f"{a['tag']}_minus_parent_fresh")
        if pr:
            row['paired_delta_vs_parent'] = pr
        pp, pc = parent_spearmans(a)
        lp, cw = j.get(f"light_probe_{a['tag']}"), \
            j.get(f"composed_wiring_{a['tag']}")
        if lp and pp is not None:
            row['plain_spearman_replicate'] = lp['wiring_spearman_all']
            row['plain_spearman_parent'] = pp
            row['delta_plain_spearman'] = round(
                lp['wiring_spearman_all'] - pp, 4)
            spreads_sp.append(abs(row['delta_plain_spearman']))
        if cw and pc is not None:
            cv = cw['tables']['cov_composed']['spearman_all']
            row['cov_composed_spearman_replicate'] = cv
            row['cov_composed_spearman_parent'] = pc
            row['delta_cov_composed_spearman'] = round(cv - pc, 4)
            spreads_sp.append(abs(row['delta_cov_composed_spearman']))
        rows[a['tag']] = row
    out = {'arms': rows,
           'what_varied': 'init seed only (Q.SEED 0 -> 1); data order held '
                          'FIXED via the unchanged Q.DATA_SEED = '
                          f'{Q.DATA_SEED}, so these deltas isolate INIT '
                          'sensitivity and understate full run-to-run spread',
           'ce_seed_spread_max_abs': (round(max(spreads_ce), 5)
                                      if spreads_ce else None),
           'spearman_seed_spread_max_abs': (round(max(spreads_sp), 4)
                                            if spreads_sp else None)}
    if spreads_ce:
        out['ce_prediction_met_le_0.02'] = bool(max(spreads_ce) <= CE_PRED)
    if spreads_sp:
        big = bool(max(spreads_sp) > R1_SE)
        out['spearman_spread_exceeds_R1_SE_0.08'] = big
        out['consequence'] = (
            'Spearman seed spread exceeds the R1 sampling SE (0.08): the '
            'frontier\'s READABILITY AXIS IS SEED-DOMINATED. Every '
            'readability comparison in this program -- including the '
            'recipe-vs-frontier tradeoff table -- needs 3+ seeds per arm '
            'before any ordering claim, and single-seed Spearman gaps below '
            'the observed spread must be reported as ties.' if big else
            'Spearman seed spread stays within the R1 sampling SE (0.08): '
            'single-seed readability numbers are usable for gaps larger than '
            'the spread, and the existing frontier ordering stands without '
            'per-arm seed replication (a data-order replicate is still owed '
            'by the standing logging list).')
    E.merge(JP, 'summary_E27', out)
    print(json.dumps({'summary_E27': out}, indent=2, default=str), flush=True)


# ---------------- main ------------------------------------------------------
if __name__ == '__main__':
    E.setup()
    E.DEV = 'cpu' if E.SMOKE else 'cuda'
    if not E.SMOKE:
        e18 = E.loadj(E.jpath('qk_e18.json'))
        assert e18.get('gate1_uniform11_weight_support', {}).get('pass') \
            and e18.get('gate2_cov_composed_E9a', {}).get('pass'), \
            'qk_e18.json gates 1+2 not passed -- reused probes unvalidated'
        for a_stem in ('qk_e9_a', 'qk_e19_a'):
            assert os.path.exists(E.ckpath(a_stem)), f'{a_stem}.pt missing'

    mlr = E7R.muon_lr()
    s_c, _ = E15R.solve_slot_c(4 * Q.D)
    if not E.SMOKE:
        assert s_c == 15, s_c
    A = arms(s_c)

    if 'E27_prediction' not in E.loadj(JP):
        E.merge(JP, 'E27_prediction', {
            'registered_before_training': True,
            'finding': 'reviewer-2 R4: every frontier number rests on one '
                       'seed and one data order',
            'ce': f'CE seed spread <= {CE_PRED} nats on both arms',
            'spearman': 'UNKNOWN -- measuring the seed spread of the wiring '
                        'Spearman (plain AND covariance-composed) is the '
                        'point of this run',
            'consequence_if_spread_gt_0.08': 'the frontier\'s readability '
                                             'axis needs 3+ seeds everywhere',
            'design': 'init seed only (Q.SEED 0 -> 1); data order held FIXED '
                      f'(Q.DATA_SEED = {Q.DATA_SEED} unchanged) so the delta '
                      'isolates init sensitivity',
            'parents': {'E27a_frontier': 'qk_e19_a (E19a)',
                        'E27b_recipe': 'qk_e9_a (E9a)'}})
    if 'E27_config' not in E.loadj(JP):
        E.merge(JP, 'E27_config', {
            'seed_replicate': SEED1, 'seed_parent': SEED0,
            'data_seed': Q.DATA_SEED, 'muon_lr': mlr, 'adamw_lr': E.get_lr(),
            'E27a_group_coeff': E19R.GC19, 'E27b_group_coeff': E9R.GC9,
            'E27a_factory': 'qk_e15_reinvest_run.make_e15c(s=15) verbatim',
            'E27a_trainer': 'qk_e19_dial_run.trainer verbatim',
            'E27b_factory': 'qk_e7_evenout_run.make_e7m1 verbatim',
            'E27b_trainer': 'qk_e9_compose_run.muon_lasso_trainer verbatim',
            'slot_E27a': s_c, 'slot_E27b': E.SUB})

    # ---- positive controls, before any training ----
    for a in A:
        control_config_equality(a, mlr)
        control_seed_gate(a, mlr)

    # ---- train + measure ----
    set_seed(SEED1)
    print(f"=== Q.SEED set to {SEED1} for training (data order unchanged, "
          f"DATA_SEED {Q.DATA_SEED}) ===", flush=True)
    for a in A:
        E.train_arm(a['stem'], JP, a['tag'], a['factory'], a['gc'], lr=mlr,
                    trainer=a['trainer'],
                    extra={'optimizer': 'muon', 'seed': SEED1,
                           'data_seed': Q.DATA_SEED, 'slot': a['slot'],
                           'parent': f"{a['parent_key']} ({a['parent_stem']}, "
                                     f"seed {SEED0})",
                           'design': a['design'],
                           'varies_from_parent': 'init seed ONLY; data order '
                                                 'identical by construction'})
        control_ckpt_config(a)
        E.oldheld_record(a['stem'], a['factory'], JP, f"{a['tag']}_oldheld")
        E.paired_fresh(a['stem'], JP, a['tag'])
        if not E.SMOKE:
            fa, fb = f"{a['stem']}_heldloss.npy", \
                f"{a['parent_stem']}_heldloss.npy"
            if os.path.exists(f'{E.QK}/{fa}') \
                    and os.path.exists(f'{E.QK}/{fb}') \
                    and f"{a['tag']}_minus_parent_fresh" not in E.loadj(JP):
                E.merge(JP, f"{a['tag']}_minus_parent_fresh",
                        dict(E.paired(fa, fb, len(Q.HELD), 'parent_seed0'),
                             parent=a['parent_stem'],
                             note='paired per-token fresh held CE, '
                                  'sequence-clustered SE; replicate minus '
                                  'its seed-0 twin'))
            tp = f"{E.QK}/{a['stem']}_traj.npz"
            if os.path.exists(tp) and f"{a['tag']}_traj" not in E.loadj(JP):
                z = np.load(tp)
                E.merge(JP, f"{a['tag']}_traj",
                        {'path': os.path.basename(tp),
                         'n_snapshots': int(len(z['step'])),
                         'every': E.TRAJ_EVERY,
                         'keys': sorted(z.files),
                         'note': 'read-group-norm + slot-covariance wiring '
                                 'trajectory (standing harness upgrade)'})
        probe(a)

    summarize(A)
    print('e27 seeds run done', flush=True)
