"""Rank-one factorization of the composed MLP7-quadratic/head8-value coefficient tensor."""
from pathlib import Path
import json,time,torch
P=Path(__file__).resolve().parent
@torch.no_grad()
def main():
 torch.set_num_threads(2);tic=time.perf_counter();pf=torch.load(P/'MLP7_PHI_READERS_FOLD_V1_PROGRAM.pt',weights_only=True);fold=torch.load(P/'ATTENTION8_PHI_READER_FOLD_V1_PROGRAM.pt',weights_only=True);gen=torch.load(P/'SCALAR_VALUE_GENERATOR_MLP8_V1_PROGRAM.pt',weights_only=True);eig=gen['eigenvalues'][:4];C=fold['head_output_readers'][2]
 files=json.loads((P/'PHI4_PROVENANCE_V1_BINDING.json').read_text())['files'];sd=torch.load(next(k for k in files if k.endswith('pytorch_model.bin')),weights_only=True,mmap=True);L=sd['transformer.h.7.mlp.Left.weight'].double();R=sd['transformer.h.7.mlp.Right.weight'].double();cc=pf['product_coefficients']*pf['lambda8'][0];M=torch.stack([(L.T*cc[i])@R for i in range(4)]);M=(M+M.transpose(-1,-2))/2;G=M.flatten(1)@M.flatten(1).T;ev,vec=torch.linalg.eigh(G);assert ev.min()>0;root=(vec*ev.sqrt())@vec.T;inv=(vec*ev.rsqrt())@vec.T;target=root@(eig[:,None]*C);u,s,vh=torch.linalg.svd(target,full_matrices=False);alpha=inv@u[:,0];vr=s[0]*vh[0];beta=torch.linalg.lstsq(C.T,vr).solution;right_error=float((beta@C-vr).norm()/vr.norm());assert right_error<1e-12
 parent=torch.load(P/'MLP7_PHI_PARENTS_V1_ARTIFACT.pt',weights_only=True);prov=torch.load(P/'PHI4_PROVENANCE_V1_ARTIFACT.pt',weights_only=True);head=torch.load(P/'ATTENTION8_PHI_HEADS_V1_ARTIFACT.pt',weights_only=True);hh=head['head_readings'][:,:,2];old=json.loads((P/'SCALAR_NEW_ENDPOINTS_V1_ROWS.json').read_text())['rows'][:24];fresh=json.loads((P/'MLP8_VALUE_FRESH_V1_ROWS.json').read_text())['rows'];rows=old+[dict(r,donor_id=r['donor_id']+24) for r in fresh];gain=float(gen['lambdas'][0]);reference=head['head_donor_fields'][:,:,2];fields=torch.zeros_like(reference);exact=torch.zeros_like(reference)
 for i,row in enumerate(rows):
  j=row['donor_id'];n=len(row['ids']);pos=int(prov['cue_positions'][i]);q=parent['parents'][i,:n,1];dh=hh[j,:n]-hh[i,:n];den=parent['rho8_squared'][i,:n];dv=2*(q@alpha)*(dh@beta)/den;dexact=2*(q*dh*eig).sum(-1)/den;dv[:pos+1]=0;dexact[:pos+1]=0;route=prov['gamma'][i,:n,:n];factor=gain/prov['rho9'][i,:n];fields[i,:n]=route@(dv*factor);exact[i,:n]=route@(dexact*factor)
 rel=lambda a,b:float((a-b).norm()/b.norm().clamp_min(1e-30));errors=[rel(fields[k*24:(k+1)*24],reference[k*24:(k+1)*24]) for k in range(4)];program=dict(q_read_coefficients=alpha,head_read_coefficients=beta,preOV_scalar_reader=vr,current_scalar_reader=beta@fold['current_value_readers'][2],first_scalar_reader=beta@fold['first_value_readers'][2],mlp7_product_coefficients=2*pf['lambda8'][0]*(alpha@pf['product_coefficients']))
 result=dict(composed_rank1_weight_capture=float(s[0].square()/s.square().sum()),group_field_errors=errors,all_group_10percent_pass=all(x<=.1 for x in errors),exact_field_error=rel(exact,reference),right_decode_error=right_error,quadratic_Gram_condition=float(ev.max()/ev.min()),singular_values=s.tolist(),program_scalars=sum(t.numel() for t in program.values()),seconds=time.perf_counter()-tic,scope='Weight-only optimalrank1 separated quadratic/headvalue coefficientFrob objective via4x4quadraticGram. NativeQK/norm/inputsgiven; no optimalityguarantee fornormalizedtext function ornativeeffect. Alternative to uncomposedHmetric, notdatafit.')
 assert result['exact_field_error']<1e-10
 torch.save(program,P/'ATTENTION8_PHI_COMPOSED_SCALAR_V1_PROGRAM.pt');(P/'ATTENTION8_PHI_COMPOSED_SCALAR_V1_RESULT.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':main()
