#!/usr/bin/env python3
"""CPU audit of the bracket native-relative key transport null."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RUNNER=ROOT/'basis_aligned/bilinear_quotient/ops/run_bracket_key2_native_relative_transport_v1.py';RESULT=ROOT/'basis_aligned/polynomial_causal/BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_RESULT.json';OUT=ROOT/'basis_aligned/polynomial_causal/BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_AUDIT.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 r=json.loads(RESULT.read_text());fit=r['fit'];checks={'runner_hash_bound':r['runner_sha256']==sha(RUNNER),'valid_terminal':r['terminal']=='native_relative_key_fit_null','literal_verdict':r['predictions']=={'pred_a_exact_instrument_and_capability':True,'pred_b_key2_transport_improves':False,'pred_c_fit_program_selected':False,'pred_d_fresh_program_transfers':False,'pred_e_control_selectivity':False},'no_selection':r['selected'] is None and r['select'] is None,'key2_not_improved':fit['key2_relative_l2_improvement']<.05,'both_candidates_fail':not fit['reports']['relative_key2']['passes'] and not fit['reports']['relative_both']['passes'],'fit_instrument':fit['instrument'] and fit['parent_live'],'exact_null_price':r['price']['observed_forwards']==6 and r['price']['observed_sequences']==864 and r['fits']==r['backwards']==r['updates']==0 and not r['quantized']}
 a={'schema':'bracket_key2_native_relative_transport_v1_audit','result_sha256':sha(RESULT),'runner_sha256':sha(RUNNER),'checks':checks,'all_checks_pass':all(checks.values()),'absolute_key2_relative_l2':fit['key2_metrics']['absolute']['relative_l2_error'],'relative_key2_relative_l2':fit['key2_metrics']['relative']['relative_l2_error'],'key2_relative_l2_improvement':fit['key2_relative_l2_improvement'],'relative_key2_behavior_relative_l2':fit['reports']['relative_key2']['overall']['relative_l2_error'],'relative_both_behavior_relative_l2':fit['reports']['relative_both']['overall']['relative_l2_error'],'finding':'Adding the frozen donor-minus-recipient type displacement to native recipient keys does not recover donor key context. It worsens key2 vector error and both donor-free behavioral programs fail on FIT, leaving the eighth construction sealed.'};OUT.write_text(json.dumps(a,indent=2,sort_keys=True)+'\n');print(json.dumps(a,indent=2,sort_keys=True))
if __name__=='__main__':main()
