#!/usr/bin/env python3
"""CPU audit of the outcome-blind bracket factor2 scalar null."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RUNNER=ROOT/'basis_aligned/bilinear_quotient/ops/run_bracket_key2_query_context_scalar_v1.py';RESULT=ROOT/'basis_aligned/polynomial_causal/BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_RESULT.json';OUT=ROOT/'basis_aligned/polynomial_causal/BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_AUDIT.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 r=json.loads(RESULT.read_text());checks={'runner_hash_bound':r['runner_sha256']==sha(RUNNER),'valid_terminal':r['terminal']=='query_context_scalar_null','literal_verdict':r['predictions']=={'pred_a_exact_factor_instrument':True,'pred_b_anchored_scalar_transfers':False,'pred_c_two_scalar_transfers':False,'pred_d_query_context_scalar_selected':False},'no_selection':r['selected'] is None,'anchored_worsens':r['candidate_reports']['anchored']['relative_l2_improvement']<0,'two_scalar_worsens':r['candidate_reports']['two_scalar']['relative_l2_improvement']<0,'exact_instrument':r['instrument']=={'replay_max_logit_error':0.0,'train_target_endpoints':216,'fit_target_endpoints':72},'exact_price':r['price']=={'forwards':5,'sequences':720,'fits':2,'backwards':0,'updates':0} and not r['quantized']};a={'schema':'bracket_key2_query_context_scalar_v1_audit','result_sha256':sha(RESULT),'runner_sha256':sha(RUNNER),'checks':checks,'all_checks_pass':all(checks.values()),'baseline_relative_l2':r['absolute_fit_metrics']['relative_l2_error'],'anchored_relative_l2':r['candidate_reports']['anchored']['metrics']['relative_l2_error'],'two_scalar_relative_l2':r['candidate_reports']['two_scalar']['metrics']['relative_l2_error'],'finding':'Neither the anchored nor free two-scalar query-context law transfers factor2 activation to the seventh construction; both worsen the frozen absolute prototype baseline, with no behavioral access and no opening of the eighth panel.'};OUT.write_text(json.dumps(a,indent=2,sort_keys=True)+'\n');print(json.dumps(a,indent=2,sort_keys=True))
if __name__=='__main__':main()
