"""Weight-level parent/child identity with explicit retained remainder."""
from pathlib import Path
import json,torch
P=Path(__file__).resolve().parent
@torch.no_grad()
def main():
 torch.set_num_threads(2);torch.manual_seed(241328);g=torch.load(P/'SCALAR_VALUE_GENERATOR_MLP8_V1_PROGRAM.pt',weights_only=True);p=torch.load(P/'extracted_circuits/regional_even_key_producers_8_2_9_8_v1/program.pt',weights_only=True);b=json.loads((P/'PHI4_PROVENANCE_V1_BINDING.json').read_text())['files'];sd=torch.load(next(k for k in b if k.endswith('pytorch_model.bin')),weights_only=True,mmap=True);r=g['reader'].double();u=g['eigenvectors'][:,:4];eig=g['eigenvalues'][:4];M4=(u*eig)@u.T;Mrest=g['matrix']-M4;readererror=float((r-p['current_value_reader']).norm()/r.norm());L=sd['transformer.h.8.mlp.Left.weight'].double();R=sd['transformer.h.8.mlp.Right.weight'].double();D=sd['transformer.h.8.mlp.proj.weight'].double() if 'transformer.h.8.mlp.proj.weight' in sd else sd['transformer.h.8.mlp.Down.weight'].double();bias=sd['transformer.h.8.mlp.Down_bias'].double()
 components=torch.randn(4,12,1152,dtype=torch.float64);z=components.sum(0);norm8=z.square().mean(-1)+torch.finfo(torch.float32).eps;x=z/norm8.sqrt()[:,None];native=((x@L.T)*(x@R.T))@D.T+bias;reads=components@u;B,Q,Hfirst,Hother=reads;whole=(reads.sum(0).square()*eig).sum(-1);child=2*(Q*Hfirst*eig).sum(-1);other=whole-child;quadrest=(z*(z@Mrest)).sum(-1);expanded=(child+other+quadrest)/norm8+g['bias_read'];rel=lambda a,b:float((a-b).norm()/b.norm().clamp_min(1e-30));result=dict(parent_reader_identity_error=readererror,full_MLP8_reader_expansion_error=rel(expanded,native@r),fourmode_numerator_partition_error=rel(child+other,whole),scope='Weight identity: samehead9current-value reader; fourmodecrossfirst plusretainedotherterms plusM8-M4 andbias exactlyreconstructreadMLP8. RandomFP64algebra control, notnativecausalparent/remaindercomposition orsemanticremainderidentification.',double_counting_rule='Removing parent andchild asindependentcomponents subtractschild twice. Use disjoint child+remainder atsameoutputinterface, then testphysicalcomposition.')
 assert readererror<1e-12 and result['full_MLP8_reader_expansion_error']<1e-10;(P/'CROSSFIRST_PARENTAGE_V1_RESULT.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':main()
