"""Export a mediator with edited RMS generated from native factors."""
from pathlib import Path
import hashlib,json,shutil
P=Path(__file__).resolve().parent

def main():
 target=P/'extracted_circuits/city_mlp8_norm_closed_v1';target.mkdir(exist_ok=True)
 shutil.copyfile(P/'mlp8_value_norm_closed_v1.py',target/'execute.py');shutil.copyfile(P/'CITY_MLP8_NORM_CLOSED_V1_PROGRAM.pt',target/'program.pt')
 local=json.loads((P/'CITY_MLP8_NORM_CLOSED_V1_CPU_RESULT.json').read_text());installed=json.loads((P/'CITY_MLP8_NORM_CLOSED_INSTALLED_V1_RESULT.json').read_text());iso_path=P/'CITY_MLP8_NORM_CLOSED_V1_ISOLATED_RESULT.json';iso=json.loads(iso_path.read_text())['passes'] if iso_path.exists() else None
 m={'schema':'regional.city_mlp8_norm_closed.v1','name':target.name,'certified_complete':False,'counterfactual':'MLP8-induced head9.8 current-value correction for subtraction under native head8.2 cityswap; editedRMS9 generated by native factors.','ports':['z8[1,T,1152] native unnormalized MLP8 input','delta[1,T,1152] upstream intervention','token_ids[1,T]'],'native_vector_state_arrays':1,'native_scalar_state_arrays':0,'intervention_vector_arrays':1,'native_state_scalars_T32':36864,'intervention_scalars_T32':36864,'static_float_scalars':local['stored_float_scalars'],'weight_bytes':local['stored_float_bytes'],'token_id_bytes':local['stored_integer_bytes'],'supported_sequence_tokens':local['tokens'],'derived_cache_bytes':local['derived_folded_down_bytes'],'runtime_float_array_bytes':local['runtime_float_bytes'],'external_computation':'Native z8 and upstreamswapdelta generation, full later suffix. This is not token-only.','four_traits':{'ood_prediction':None,'extraction':iso and all(installed['pred_'+k] for k in 'abc') if iso is not None else None,'selective_removal':None,'composition_reuse':False},'property_scope':'Exact native-factor closure validated on opened fixtures; fresh mediator evidence belongs to prior supplied-norm interface until expanded-generator fresh confirmation. Related direct/MLP8 independent pair fails fresh reversed-group composition; no matched-effect simplicity claim.','evidence':{'local':'../../CITY_MLP8_NORM_CLOSED_V1_CPU_RESULT.json','installed':'../../CITY_MLP8_NORM_CLOSED_INSTALLED_V1_RESULT.json','isolated':'../../CITY_MLP8_NORM_CLOSED_V1_ISOLATED_RESULT.json','prior_fresh_mediator':'../../CITY_VALUE_MEDIATION_FRESH_V1_RESULT.json','failed_pair_composition':'../../CITY_VALUE_PATH_FRESH_V1_RESULT.json'},'files':{f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in target.iterdir() if f.suffix in ['.py','.pt']}}
 (target/'manifest.json').write_text(json.dumps(m,indent=2)+'\n')
 (target/'README.md').write_text('''# MLP8 value mediator with generated edited RMS

`runtime=execute.prepare(torch.load("program.pt",weights_only=True))`, then
`execute.execute(runtime,z,delta,token_ids)` returns the FP64[1,T,128] value correction.
Only these files and PyTorch are needed. CPU batch1; native z8 and upstreamdelta
are[1,T,1152];token IDs[1,T]. Frozen402-token vocabulary; unsupported tokens/batch>1 fail.

The program computes normalized bilinear MLP8 hidden products, edited MLP8 output
including bias, block9 residual/reentry mixing and editedRMS9. It folds the head9.8
value reader into Down8 once at prepare time. No supplied native norm or edited
residual state remains. The initial-token table is checkpoint-derived, not fitted.

Subtract output from head9.8 value while retaining the upstream cityswap, bothkeys,
otherheads and nativefullsuffix. Nativez8 and the interventiondelta still require
external computation. No token-only, independentcomposition or storagewin claim.

Price16,536,963FP32values/66,147,852bytes plus3,216token-IDbytes. Derived FP64fold
cache589,824values/4,718,592bytes. FP64runtime factor arrays137,014,296bytes before
activation workspace. Nativez8 atT32 is36,864scalars;delta36,864intervention scalars
counted separately. Storedweights increase versus the suppliednorm interface.

See manifest for opened local/installed/isolated evidence. Fresh confirmation of
this expanded generator remains pending. Preserve prior fresh-mediator evidence
and failed direct/MLP8 composition as separately scoped results.
''')
if __name__=='__main__':main()
