"""Exact normalized-cut derivative for orthogonal block projectors."""
import json
from pathlib import Path
import torch
from fullu_input_blocks_v1 import sandwich, partition_metrics


def objective_gradient(l,r,g,p,k):
    t=torch.trace(k);a=torch.trace(p@k)
    phi=sandwich(l,r,g,p)
    c=a-torch.trace(p@phi)
    scale=t/(a*(t-a))
    euclidean=scale*(k-2*phi)-c*t*(t-2*a)/(a*a*(t-a)**2)*k
    tangent=p@euclidean+euclidean@p-2*p@euclidean@p
    return c*scale,euclidean,tangent


def control():
    torch.set_default_dtype(torch.float64)
    rng=torch.Generator().manual_seed(120431)
    l,r=[torch.randn(12,8,generator=rng) for _ in range(2)]
    w=torch.randn(10,12,generator=rng);g=w.T@w
    k=sandwich(l,r,g,torch.eye(8))
    q=torch.linalg.qr(torch.randn(8,8,generator=rng)).Q[:,:4];p=q@q.T
    value,gradient,tangent=objective_gradient(l,r,g,p,k)
    omega=torch.randn(8,8,generator=rng);omega=(omega-omega.T)/2
    direction=omega@p-p@omega
    eps=1e-5
    values=[]
    for step in (-eps,eps):
        rotation=torch.matrix_exp(step*omega)
        pp=rotation@p@rotation.T
        values.append(partition_metrics(l,r,g,pp,k)['normalized_cut'])
    fd=(values[1]-values[0])/(2*eps)
    analytic=float((gradient*direction).sum())
    derivative_error=abs(fd-analytic)/max(1.,abs(analytic))
    # Projector-preserving descent generated by the commutator [P,gradient].
    generator=p@gradient-gradient@p
    rotation=torch.matrix_exp(.01*generator)
    new=rotation@p@rotation.T
    after=partition_metrics(l,r,g,new,k)['normalized_cut']
    result=dict(derivative_relative_error=derivative_error,initial=float(value),after_small_descent=after,
                tangent_squared_norm=float(tangent.square().sum()),projector_error=float((new@new-new).norm()),
                passed=derivative_error<1e-8 and after<float(value))
    return result


if __name__=='__main__':
    result=control();Path(__file__).with_name('FULLU_BLOCK_ROTATION_V1_CONTROL.json').write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps(result));assert result['passed']
