#!/bin/bash
set -u

THREAD_ID="01a05a80-8023-7ce1-a68c-c1cd30064b89"
PROMPT="HOURLY CIRCUIT-ONLY REVIEW AND CONTINUATION. The controlling goal is to build a solid reusable codebase that can produce hundreds of high-quality, nonduplicated causal circuits, then use those circuits to solve the model's decomposition. Target one honest basic causal circuit result or informative null per roughly 10 serial minutes. Inspect current repository timestamps, git history, AGENT_BOARD, the canonical circuit dossiers/registry, active claims, result artifacts, queue, and running jobs before choosing work. Do not drift into rank reduction, quantization, activation-energy/variance, or activation reconstruction: those do not establish the circuit properties we need. Prefer task-level causal outcomes such as CE loss, answer/logit margins, interchange behavior, and selective removal effects. Enforce and record three gates: CIRCUIT_FOCUS (the hour advanced a circuit dataset, causal intervention, circuit record, or shared throughput); CEREMONY_BUDGET (basic analysis was not buried under a large suite of backup guarantees; use only the minimum checks needed for an honest result, and defer extended confirmation until a signal exists); NOVELTY_LESSON_GATE (search canonical dossiers, claims, failures, and prior results first, so no circuit or known lesson is repeated). Explicitly remember the recurring lesson that high activation reconstruction is not the scientific target; task behavior and CE are materially better checks. A high-quality circuit should have a meaningful counterfactual dataset, held-out/OOD prediction, a causal mechanism that can be extracted, selective removal or interchange without damage to unrelated behavior, and evidence about reuse/composition where applicable. Do not treat an attention head or whole MLP as the final basis when it can be causally split or grouped by computation. Check that controls are genuinely capable of failing, rather than passing a loose fixed threshold. Measure how many scientific terminals landed in the preceding hour and their serial times; if a basic screen exceeds about 10 minutes, identify the exact engineering bottleneck and simplify/refactor before adding checks. Coordinate with Claude through AGENT_BOARD so both lanes work only on circuits and do not duplicate a claimed family, dataset, or lesson. After the review, immediately execute the highest-information safe unblocked circuit action; do not stop at a plan or status report, and do not wait for user confirmation for safe in-scope work. If a GPU job is running, advance a different claimed circuit or shared circuit tooling. Preserve nulls and update the canonical record so later agents cannot repeat the work."

exec /opt/nvm/versions/node/v24.19.0/bin/codex queue \
    --thread "$THREAD_ID" \
    --message "$PROMPT"
