#!/usr/bin/env python3
from copy import deepcopy
import json,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[1];BQ=REPO/'basis_aligned/bilinear_quotient';sys.path.insert(0,str(BQ))
from circuit_registry_v2 import _atomic_json,_lock,circuit_path,design_key,execution_key,file_sha256,rebuild_registry_v2,validate_v2
TAG='task.subject_verb.number_agreement';OLD='grammatical_subject_number.v29';NEW='grammatical_subject_number.v30';EVENT='subject_number_native_scalar_feature_discovery.v1.complete.null';RESULT=BQ/'circuits/fast_screens/subject_number_native_scalar_feature_discovery_v1_result.json';AUDIT=HERE/'SUBJECT_NUMBER_NATIVE_SCALAR_FEATURE_DISCOVERY_V1_AUDIT.json'
ART={'subject_native_scalar_discovery_prereg_v1':('basis_aligned/polynomial_causal/SUBJECT_NUMBER_NATIVE_SCALAR_FEATURE_DISCOVERY_V1_PREREGISTRATION.md','preregistration'),'subject_native_scalar_discovery_binding_v1':('basis_aligned/polynomial_causal/SUBJECT_NUMBER_NATIVE_SCALAR_FEATURE_DISCOVERY_V1_BINDING.json','binding'),'subject_native_scalar_discovery_runner_v1':('basis_aligned/bilinear_quotient/ops/run_subject_number_native_scalar_feature_discovery_v1.py','runner'),'subject_native_scalar_discovery_result_v1':('basis_aligned/bilinear_quotient/circuits/fast_screens/subject_number_native_scalar_feature_discovery_v1_result.json','result'),'subject_native_scalar_discovery_auditor_v1':('basis_aligned/polynomial_causal/audit_subject_number_native_scalar_feature_discovery_v1.py','audit'),'subject_native_scalar_discovery_audit_v1':('basis_aligned/polynomial_causal/SUBJECT_NUMBER_NATIVE_SCALAR_FEATURE_DISCOVERY_V1_AUDIT.json','audit')}
def art(p,k):return {'path':p,'sha256':file_sha256(REPO/p),'kind':k,'status':'frozen'}
def m(n,e,b):return {'name':n,'estimate':e,'ci95':None,'bar':b}
def main():
 r=json.loads(RESULT.read_text());a=json.loads(AUDIT.read_text());assert a['all_checks_pass'];path=circuit_path(TAG)
 with _lock('registry'):
  record=json.loads(path.read_text());assert record['claims'][-1]['claim_id']==OLD
  for aid,s in ART.items():record['artifacts'][aid]=art(*s)
  prev=record['claims'][-1];claim=deepcopy(prev);claim.update({'claim_id':NEW,'revision':30,'supersedes':OLD,'evidence_event_ids':[*prev['evidence_event_ids'],EVENT],'next_missing':'Native base-L11H3 coordinates predict subject-program sign but not amplitude across constructions (best rank2 relative L2 .58757; cardinality4 .92182). Next read direction/cardinality from the upstream E/A/U/W residual factors or their finite interactions; do not widen the base-head singular readout, fit behavior, or use quantization.'});record['claims'].append(claim);s=r['reports']['2'];event={'event_id':EVENT,'claim_id':NEW,'test_type':'compiled_equivalence','stage':'complete','verdict':'null','failure_kind':'scientific_null','family_ids':[],'site_id':'L11H3.projected_write.direction_cardinality_rank1_program','split_plan_id':None,'evaluation_role':'opened_construction_native_activation_feature_discovery','metrics':[m('rank2_cross_construction_cosine',s['cross_construction']['cosine'],'report'),m('rank2_cross_construction_relative_l2',s['cross_construction']['relative_l2_error'],'<=.50'),m('rank2_sign_agreement',s['cross_construction']['sign_agreement'],'report'),m('rank2_cardinality4_relative_l2',s['by_cardinality']['4']['relative_l2_error'],'report')],'prereg_artifact_id':'subject_native_scalar_discovery_prereg_v1','result_artifact_id':'subject_native_scalar_discovery_result_v1','input_artifact_ids':list(ART),'seed':None,'checkpoint_sha256':r['checkpoint_weights_sha256'],'supersedes_event_id':None,'replicates_event_id':None,'sections':[],'notes':'Outcome-blind program-label discovery on opened constructions; 12 OLS fits, no exact donor displacement, behavior, fresh authority, gradients, updates, or quantization.'};event['design_key']=design_key(record,event);event['execution_key']=execution_key(record,event);record['evidence_events'].append(event);validate_v2(record);_atomic_json(path,record)
 rebuild_registry_v2();print(json.dumps({'status':'registered','claim_id':NEW,'event_id':EVENT},indent=2))
if __name__=='__main__':main()
