#!/usr/bin/env python3
"""Register the selected one-parameter live-amplitude bracket suffix law."""
from copy import deepcopy
import json
from pathlib import Path
import sys
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[1];BQ=REPO/"basis_aligned/bilinear_quotient";sys.path.insert(0,str(BQ))
from circuit_registry_v2 import _atomic_json,_lock,circuit_path,design_key,execution_key,file_sha256,rebuild_registry_v2,validate_v2
TAG="task.bracket_pending_opener";OLD="pending_opener_state.v35";NEW="pending_opener_state.v36";EVENT="pending_opener.suffix_live_direct_amplitude.selected.v1";RESULT=HERE/"BRACKET_SUFFIX_LIVE_AMPLITUDE_SELECTION_V1_RESULT.json"
ARTIFACTS={"suffix_live_amplitude_v1_prereg":("basis_aligned/polynomial_causal/BRACKET_SUFFIX_LIVE_AMPLITUDE_SELECTION_V1_PREREGISTRATION.md","preregistration"),"suffix_live_amplitude_v1_binding":("basis_aligned/polynomial_causal/BRACKET_SUFFIX_LIVE_AMPLITUDE_SELECTION_V1_BINDING.json","binding"),"suffix_live_amplitude_v1_runner":("basis_aligned/bilinear_quotient/ops/run_bracket_suffix_live_amplitude_selection_v1.py","runner"),"suffix_live_amplitude_v1_result":("basis_aligned/polynomial_causal/BRACKET_SUFFIX_LIVE_AMPLITUDE_SELECTION_V1_RESULT.json","result")}
def art(p,k):return {"path":p,"sha256":file_sha256(REPO/p),"kind":k,"status":"frozen"}
def main():
 result=json.loads(RESULT.read_text());assert result["terminal"]=="live_amplitude_law_selected" and all(result["predictions"].values());program=result["selected_program"];assert program["law"]=="global_direct" and program["parameter_count"]==1 and not program["future_rows_accessed"]
 path=circuit_path(TAG);current=json.loads(path.read_text())
 if any(e["event_id"]==EVENT for e in current["evidence_events"]):validate_v2(current);rebuild_registry_v2();print("already registered");return
 with _lock("registry"):
  record=json.loads(path.read_text());previous=next(c for c in record["claims"] if c["claim_id"]==OLD)
  for aid,spec in ARTIFACTS.items():record["artifacts"][aid]=art(*spec)
  claim=deepcopy(previous);claim.update({"claim_id":NEW,"revision":36,"supersedes":OLD,"evidence_event_ids":[*previous["evidence_event_ids"],EVENT],"next_missing":"A single global coefficient on the live donor-free source delta's direct donor-minus-recipient LM-head projection cross-transfers fifth-to-sixth and sixth-to-fifth with .1369/.1461 relative error, cosine .9922/.9911, and sign 1.0; it is simpler than every pair-conditioned passing law. The pooled frozen coefficient is 0.0005561862682518956. Next confirm this exact coefficient with the frozen donor-free rank-two source generator on a seventh construction generated only after selection; no coefficient/rank change, construction feature, intercept, refit, or quantization."});site={"site_id":"pending_opener.suffix_direct_readout_live_amplitude","tensor_path":"0.0005561862682518956 times dot(donor-free L13H8 source delta, LM-head donor closer row minus recipient closer row)","shape":["batch",1],"intervention":"predict donorward closer-margin effect without executing the native suffix","ceiling_event_ids":[EVENT]};claim["candidate_sites"].append(site);record["claims"].append(claim)
  f=result["candidate_reports"]["global_direct"];event={"event_id":EVENT,"claim_id":NEW,"test_type":"composition","stage":"complete","verdict":"held","failure_kind":None,"family_ids":["layered_pending_stack_top","embedded_pending_stack_top"],"site_id":site["site_id"],"split_plan_id":None,"evaluation_role":"opened_panels_bidirectional_selection_before_future_confirmation","metrics":[{"name":"fifth_to_sixth_relative_l2","estimate":f["fifth_to_sixth"]["metrics"]["relative_l2_error"],"ci95":None,"bar":"<=0.40"},{"name":"sixth_to_fifth_relative_l2","estimate":f["sixth_to_fifth"]["metrics"]["relative_l2_error"],"ci95":None,"bar":"<=0.40"},{"name":"selected_parameter_count","estimate":program["parameter_count"],"ci95":None,"bar":"minimum among passing"}],"prereg_artifact_id":"suffix_live_amplitude_v1_prereg","result_artifact_id":"suffix_live_amplitude_v1_result","input_artifact_ids":list(ARTIFACTS),"seed":None,"checkpoint_sha256":result["checkpoint_sha256"],"supersedes_event_id":None,"replicates_event_id":None,"sections":["basis_aligned/polynomial_causal/BRACKET_SUFFIX_LIVE_AMPLITUDE_SELECTION_V1_PREREGISTRATION.md"],"notes":"Selection used only opened fifth/sixth program effects. Seventh rows did not exist. No construction feature, intercept, rank change, update, or quantization."};event["design_key"]=design_key(record,event);event["execution_key"]=execution_key(record,event);record["evidence_events"].append(event);validate_v2(record);_atomic_json(path,record)
 rebuild_registry_v2();final=json.loads(path.read_text());validate_v2(final);print(json.dumps({"status":"registered","claim_id":NEW,"event_id":EVENT},indent=2))
if __name__=="__main__":main()
