#!/usr/bin/env python3
"""Register held strong-direction subject-number composition."""
from copy import deepcopy
import json,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[1];BQ=REPO/'basis_aligned/bilinear_quotient';sys.path.insert(0,str(BQ))
from circuit_registry_v2 import _atomic_json,_lock,circuit_path,design_key,execution_key,file_sha256,rebuild_registry_v2,validate_v2
TAG='task.subject_verb.number_agreement';OLD='grammatical_subject_number.v26';NEW='grammatical_subject_number.v27';EVENT='subject_number_two_site_strong_direction.v2.complete.held';RESULT=HERE/'SUBJECT_NUMBER_TWO_SITE_COMPOSITION_V2_RESULT.json'
ARTIFACTS={'subject_number_two_site_builder_v2':('basis_aligned/polynomial_causal/build_subject_number_two_site_composition_v2_rows.py','builder'),'subject_number_two_site_test_v2':('basis_aligned/polynomial_causal/test_build_subject_number_two_site_composition_v2_rows.py','test'),'subject_number_two_site_rows_v2':('basis_aligned/polynomial_causal/SUBJECT_NUMBER_TWO_SITE_COMPOSITION_V2_ROWS.json','rows'),'subject_number_two_site_prereg_v2':('basis_aligned/polynomial_causal/SUBJECT_NUMBER_TWO_SITE_COMPOSITION_V2_PREREGISTRATION.md','preregistration'),'subject_number_two_site_binding_v2':('basis_aligned/polynomial_causal/SUBJECT_NUMBER_TWO_SITE_COMPOSITION_V2_BINDING.json','binding'),'subject_number_two_site_runner_v2':('basis_aligned/bilinear_quotient/ops/run_subject_number_two_site_composition_v2.py','runner'),'subject_number_two_site_result_v2':('basis_aligned/polynomial_causal/SUBJECT_NUMBER_TWO_SITE_COMPOSITION_V2_RESULT.json','result'),'subject_number_two_site_audit_v2':('basis_aligned/polynomial_causal/SUBJECT_NUMBER_TWO_SITE_COMPOSITION_V2_AUDIT.json','audit')}
def art(p,k):return {'path':p,'sha256':file_sha256(REPO/p),'kind':k,'status':'frozen'}
def m(n,e,b):return {'name':n,'estimate':e,'ci95':None,'bar':b}
def main():
 r=json.loads(RESULT.read_text());a=json.loads((HERE/'SUBJECT_NUMBER_TWO_SITE_COMPOSITION_V2_AUDIT.json').read_text());assert r['terminal']=='two_site_additive_composition' and a['all_checks_pass'];path=circuit_path(TAG)
 with _lock('registry'):
  record=json.loads(path.read_text());assert record['claims'][-1]['claim_id']==OLD
  for aid,spec in ARTIFACTS.items():record['artifacts'][aid]=art(*spec)
  previous=record['claims'][-1];claim=deepcopy(previous);claim.update({'claim_id':NEW,'revision':27,'supersedes':OLD,'evidence_event_ids':[*previous['evidence_event_ids'],EVENT],'next_missing':'The frozen cardinality-four singular-to-plural rank-one program is now prospectively composable at two fresh subject sites: both single writes are live/selective and their joint behavioral effect is additive to 6.92e-5 relative L2 with no anticausal effect. The plural-to-singular direction remains weak under the same authority. Next derive the axis/scalar from native text state or test a fresh multi-site mixed context with independently live coefficients; do not refit the axis, rescue the weak reverse coefficient, or add a composition interaction.'});family={'family_id':'fresh_two_clause_subject_number_strong_direction_v2','role':'interchange','changes':['same frozen singular-to-plural rank-one write at site 1','same frozen singular-to-plural rank-one write at site 2'],'holds_fixed':['fresh two-clause tokens','native downstream background','rank-one axis','cardinality-four coefficient'],'builder_artifact_id':'subject_number_two_site_builder_v2','control_ids':['zero replay','site2 anticausal check','can-versus-will margin'],'split_plan_id':None,'status':'validated'};claim['counterfactual_families'].append(family);record['claims'].append(claim)
  event={'event_id':EVENT,'claim_id':NEW,'test_type':'composition','stage':'complete','verdict':'held','failure_kind':None,'family_ids':[family['family_id']],'site_id':'L11H3.projected_write.direction_cardinality_rank1_program','split_plan_id':None,'evaluation_role':'prospective_fresh_strong_direction_two_site_composition','metrics':[m('site1_effect_rms',r['single_site']['site1|singular_to_plural']['effect_rms'],'>=.01'),m('site2_effect_rms',r['single_site']['site2|singular_to_plural']['effect_rms'],'>=.01'),m('overall_composition_cosine',r['composition']['overall']['cosine'],'>=.95'),m('overall_composition_relative_l2',r['composition']['overall']['relative_l2_error'],'<=.25'),m('overall_sign_agreement',r['composition']['overall']['sign_agreement'],'>=.90'),m('interaction_over_joint_rms',r['interaction_over_joint_rms'],'<.20 for additive verdict'),m('joint_unrelated_control_fraction',r['joint_unrelated_control_fraction'],'<=.75'),m('anticausal_max_absolute_effect',r['anticausal_site2_to_site1_max_absolute_effect'],'<=1e-5')],'prereg_artifact_id':'subject_number_two_site_prereg_v2','result_artifact_id':'subject_number_two_site_result_v2','input_artifact_ids':list(ARTIFACTS),'seed':None,'checkpoint_sha256':r['checkpoint_sha256'],'supersedes_event_id':None,'replicates_event_id':None,'sections':[],'notes':'Fresh lexicon/templates, immutable axis and coefficient, zero fits/gains/rank changes/updates/quantization. V2 independently avoids V1’s known weak reverse direction.'};event['design_key']=design_key(record,event);event['execution_key']=execution_key(record,event);record['evidence_events'].append(event);validate_v2(record);_atomic_json(path,record)
 rebuild_registry_v2();print(json.dumps({'status':'registered','claim_id':NEW,'event_id':EVENT},indent=2))
if __name__=='__main__':main()
