#!/usr/bin/env python3
"""Register bracket source transfer and fixed suffix-scalar null on construction six."""
from copy import deepcopy
import json
from pathlib import Path
import sys
HERE=Path(__file__).resolve().parent; REPO=HERE.parents[1]; BQ=REPO/"basis_aligned/bilinear_quotient"; sys.path.insert(0,str(BQ))
from circuit_registry_v2 import _atomic_json,_lock,circuit_path,design_key,execution_key,file_sha256,rebuild_registry_v2,validate_v2
TAG="task.bracket_pending_opener"; OLD="pending_opener_state.v34"; NEW="pending_opener_state.v35"; EVENT="pending_opener.embedded_compact_behavior.fixed_scalar_null.v1"; RESULT=HERE/"BRACKET_EMBEDDED_PENDING_COMPACT_BEHAVIOR_V1_RESULT.json"
ARTIFACTS={"embedded_pending_rows_builder_v1":("basis_aligned/polynomial_causal/build_bracket_embedded_pending_ood_v1_rows.py","builder"),"embedded_pending_rows_test_v1":("basis_aligned/polynomial_causal/test_build_bracket_embedded_pending_ood_v1_rows.py","test"),"embedded_pending_rows_v1":("basis_aligned/polynomial_causal/BRACKET_EMBEDDED_PENDING_OOD_V1_ROWS.json","rows"),"embedded_compact_behavior_v1_prereg":("basis_aligned/polynomial_causal/BRACKET_EMBEDDED_PENDING_COMPACT_BEHAVIOR_V1_PREREGISTRATION.md","preregistration"),"embedded_compact_behavior_v1_binding":("basis_aligned/polynomial_causal/BRACKET_EMBEDDED_PENDING_COMPACT_BEHAVIOR_V1_BINDING.json","binding"),"embedded_compact_behavior_v1_runner":("basis_aligned/bilinear_quotient/ops/run_bracket_embedded_pending_compact_behavior_v1.py","runner"),"embedded_compact_behavior_v1_result":("basis_aligned/polynomial_causal/BRACKET_EMBEDDED_PENDING_COMPACT_BEHAVIOR_V1_RESULT.json","result")}
def art(p,k):return {"path":p,"sha256":file_sha256(REPO/p),"kind":k,"status":"frozen"}
def main():
 result=json.loads(RESULT.read_text()); assert result["terminal"]=="fixed_suffix_scalar_null" and result["predictions"]=={"pred_a_exact_instrument_and_capability":True,"pred_b_exact_joint_parent_live":True,"pred_c_donor_free_source_transfers":True,"pred_d_six_scalar_predicts_exact_effect":False,"pred_e_six_scalar_predicts_program_effect":False,"pred_f_control_selectivity":True}; assert result["price"]["observed_forwards"]==4 and result["price"]["observed_sequences"]==576
 path=circuit_path(TAG); current=json.loads(path.read_text())
 if any(e["event_id"]==EVENT for e in current["evidence_events"]):validate_v2(current);rebuild_registry_v2();print("already registered");return
 with _lock("registry"):
  record=json.loads(path.read_text());previous=next(c for c in record["claims"] if c["claim_id"]==OLD)
  for aid,spec in ARTIFACTS.items():record["artifacts"][aid]=art(*spec)
  split="pending_opener_sixth_embedded_v1";record["split_plans"].append({"split_plan_id":split,"unit":"fresh sixth-construction lexical group and exact token sequence","partition_artifact_id":"embedded_pending_rows_v1","builder_artifact_id":"embedded_pending_rows_builder_v1","seed":None,"groups":{"SIXTH_CONSTRUCTION_TEST":72},"leakage_group_keys":["exact token sequence","lexical group","construction template","row id"],"sealed_before_outcomes":True,"sealed_at":"2026-09-15T00:34:48Z"})
  claim=deepcopy(previous);claim.update({"claim_id":NEW,"revision":35,"supersedes":OLD,"evidence_event_ids":[*previous["evidence_event_ids"],EVENT],"next_missing":"The frozen donor-free rank-two source generator transfers again on a sixth construction (effect cosine .9880, relative L2 .1671, sign 1.0; controls .0504 of target RMS), but the fixed six-scalar suffix law fails: pair relative errors reach .9688 against exact and 1.0609 against program effects, despite correct signs. A complete suffix-free predictor therefore needs live source amplitude. Next freeze source-delta norm and direct closer-readout projection features on already opened fifth/sixth rows, choose the lower-complexity interaction law without access to a seventh construction, and confirm once on fresh rows; do not revisit source rank, use construction labels, tune scalar gains on the test, or quantize."})
  claim["counterfactual_families"].extend([{"family_id":"embedded_pending_stack_top","role":"interchange","changes":["inner stack-top delimiter type","correct immediate closer"],"holds_fixed":["outer brace opener","middle delimiter","sixth surface and words","aligned positions"],"builder_artifact_id":"embedded_pending_rows_builder_v1","control_ids":["exact donor-term ceiling","donor-free source program","fixed suffix scalar"],"split_plan_id":split,"status":"validated"},{"family_id":"embedded_middle_change_inner_fixed","role":"invariance","changes":["middle pending delimiter type"],"holds_fixed":["outer brace opener","inner delimiter and closer","sixth words","aligned length"],"builder_artifact_id":"embedded_pending_rows_builder_v1","control_ids":["donor-free zero type difference","native capability","exact ceiling"],"split_plan_id":split,"status":"validated"}]);claim["split_plan_ids"]=[*claim.get("split_plan_ids",[]),split];record["claims"].append(claim)
  o=result["overall"];event={"event_id":EVENT,"claim_id":NEW,"test_type":"cross_family_transfer","stage":"complete","verdict":"null","failure_kind":"scientific_null","family_ids":["embedded_pending_stack_top","embedded_middle_change_inner_fixed"],"site_id":"attention13.head8.opener_type_key_payload_rank2_live_query","split_plan_id":split,"evaluation_role":"fresh_sixth_compact_source_and_suffix_test","metrics":[{"name":"source_program_effect_relative_l2","estimate":o["program_vs_exact"]["relative_l2_error"],"ci95":None,"bar":"<=0.40"},{"name":"fixed_scalar_vs_exact_relative_l2","estimate":o["scalar_vs_exact"]["relative_l2_error"],"ci95":None,"bar":"<=0.60 overall and <=0.65 each pair"},{"name":"fixed_scalar_vs_program_relative_l2","estimate":o["scalar_vs_program"]["relative_l2_error"],"ci95":None,"bar":"<=0.60 overall and <=0.65 each pair"},{"name":"fixed_scalar_vs_program_norm_ratio","estimate":o["scalar_vs_program"]["predicted_to_actual_norm_ratio"],"ci95":None,"bar":"0.50--1.50"},{"name":"control_to_target_rms","estimate":result["control_to_target_rms"],"ci95":None,"bar":"<=0.50"}],"prereg_artifact_id":"embedded_compact_behavior_v1_prereg","result_artifact_id":"embedded_compact_behavior_v1_result","input_artifact_ids":list(ARTIFACTS),"seed":None,"checkpoint_sha256":result["checkpoint_sha256"],"supersedes_event_id":None,"replicates_event_id":None,"sections":["basis_aligned/polynomial_causal/BRACKET_EMBEDDED_PENDING_COMPACT_BEHAVIOR_V1_PREREGISTRATION.md"],"notes":"Source program held prospectively; immutable suffix scalar failed pairwise amplitude bars. No fit, program/scalar change, donor state in program arm, or quantization."};event["design_key"]=design_key(record,event);event["execution_key"]=execution_key(record,event);record["evidence_events"].append(event);validate_v2(record);_atomic_json(path,record)
 rebuild_registry_v2();final=json.loads(path.read_text());validate_v2(final);print(json.dumps({"status":"registered","claim_id":NEW,"event_id":EVENT},indent=2))
if __name__=="__main__":main()
