#!/usr/bin/env python3
"""Register the valid induction finite-bilinear consumer boundary."""
from copy import deepcopy
import json,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[1];BQ=REPO/'basis_aligned/bilinear_quotient';sys.path.insert(0,str(BQ))
from circuit_registry_v2 import _atomic_json,_lock,circuit_path,design_key,execution_key,file_sha256,rebuild_registry_v2,validate_v2
TAG='task.induction.selector_payload';OLD='induction_selector_and_payload.v15';NEW='induction_selector_and_payload.v16';EVENT='induction.early_mlp_finite_bilinear_factor.v2.complete.null'
ARTIFACTS={'induction_finite_bilinear_v1_prereg':('basis_aligned/polynomial_causal/INDUCTION_EARLY_MLP_FINITE_BILINEAR_FACTOR_V1_PREREGISTRATION.md','preregistration'),'induction_finite_bilinear_v1_runner':('basis_aligned/bilinear_quotient/ops/run_induction_early_mlp_finite_bilinear_factor_v1.py','runner'),'induction_finite_bilinear_v1_result':('basis_aligned/polynomial_causal/INDUCTION_EARLY_MLP_FINITE_BILINEAR_FACTOR_V1_RESULT.json','result'),'induction_finite_bilinear_v2_prereg':('basis_aligned/polynomial_causal/INDUCTION_EARLY_MLP_FINITE_BILINEAR_FACTOR_V2_PREREGISTRATION.md','preregistration'),'induction_finite_bilinear_v2_binding':('basis_aligned/polynomial_causal/INDUCTION_EARLY_MLP_FINITE_BILINEAR_FACTOR_V2_BINDING.json','binding'),'induction_finite_bilinear_v2_runner':('basis_aligned/bilinear_quotient/ops/run_induction_early_mlp_finite_bilinear_factor_v2.py','runner'),'induction_finite_bilinear_v2_result':('basis_aligned/polynomial_causal/INDUCTION_EARLY_MLP_FINITE_BILINEAR_FACTOR_V2_RESULT.json','result'),'induction_finite_bilinear_v2_audit':('basis_aligned/polynomial_causal/INDUCTION_EARLY_MLP_FINITE_BILINEAR_FACTOR_V2_AUDIT.json','audit')}
def art(p,k):return {'path':p,'sha256':file_sha256(REPO/p),'kind':k,'status':'frozen'}
def m(n,e,b):return {'name':n,'estimate':e,'ci95':None,'bar':b}
def main():
 r=json.loads((HERE/'INDUCTION_EARLY_MLP_FINITE_BILINEAR_FACTOR_V2_RESULT.json').read_text());a=json.loads((HERE/'INDUCTION_EARLY_MLP_FINITE_BILINEAR_FACTOR_V2_AUDIT.json').read_text());assert r['terminal']=='finite_bilinear_factor_null' and a['all_checks_pass'];path=circuit_path(TAG)
 with _lock('registry'):
  record=json.loads(path.read_text());assert record['claims'][-1]['claim_id']==OLD
  for aid,spec in ARTIFACTS.items():record['artifacts'][aid]=art(*spec)
  previous=record['claims'][-1];claim=deepcopy(previous);claim.update({'claim_id':NEW,'revision':16,'supersedes':OLD,'evidence_event_ids':[*previous['evidence_event_ids'],EVENT],'next_missing':'Exact finite-amplitude MLP8-12 bilinear coordinates also fail to isolate an answer-preserving induction consumer: quadratic removal increases collateral, ordered cross removal reduces vocabulary RMS by 35-48%, but even full online response restoration leaves positive CE damage above .10. Direct axes, VJPs, typed groups, and exact early-MLP bilinear factors are now bounded. Do not tune components or bars. Reopen only with an independently derived later attention-MLP interaction interface; otherwise move circuits.'});site={'site_id':'early_mlp8_12_finite_bilinear_response','tensor_path':'online exact MLP response from recipient native normalized input to joint-edited normalized input','shape':['batch',5,1152],'intervention':'remove left-cross, right-cross, quadratic, their cross sum, or full finite response','ceiling_event_ids':[]};claim['candidate_sites'].append(site);record['claims'].append(claim)
  event={'event_id':EVENT,'claim_id':NEW,'test_type':'compiled_equivalence','stage':'complete','verdict':'null','failure_kind':'scientific_null','family_ids':['selector_payload_joint_answer_preserved'],'site_id':site['site_id'],'split_plan_id':claim['split_plan_ids'][0],'evaluation_role':'frozen discovery_confirm_finite_interaction_factorization','metrics':[m('maximum_FP64_closure_relative_squared_error',r['instrument']['maximum_bilinear_closure_relative_squared_error'],'<=1e-10'),m('discovery_passing_compact_factors',0,'>=1'),m('cross_removal_vocab_RMS_reduction_range',a['cross_removal_reduction_range'],'>=.25 each cell'),m('full_removal_positive_CE_damage_range',a['full_removal_positive_ce_damage_range'],'<=.10 each cell'),m('forwards',r['price']['forwards'],'24'),m('sequences',r['price']['sequences'],'768')],'prereg_artifact_id':'induction_finite_bilinear_v2_prereg','result_artifact_id':'induction_finite_bilinear_v2_result','input_artifact_ids':list(ARTIFACTS),'seed':None,'checkpoint_sha256':r['checkpoint_sha256'],'supersedes_event_id':None,'replicates_event_id':None,'sections':[],'notes':'V1 was instrument-invalid at the FP32 closure check. V2 changes only that check to FP64; causal tensors and all outcomes are unchanged. Zero fits, gradients, updates, gains, or quantization.'};event['design_key']=design_key(record,event);event['execution_key']=execution_key(record,event);record['evidence_events'].append(event);validate_v2(record);_atomic_json(path,record)
 rebuild_registry_v2();print(json.dumps({'status':'registered','claim_id':NEW,'event_id':EVENT},indent=2))
if __name__=='__main__':main()
