[program:bqrunner2]
environment=PROC_NAME="%(program_name)s",HF_HOME="/workspace/.hf_home",PYTHONPATH="/workspace/tensor_language:/workspace/tensor_language/basis_aligned/polynomial_causal:/workspace/tensor_language/basis_aligned/bilinear_quotient",CUDA_VISIBLE_DEVICES=""
command=/workspace/tensor_language/basis_aligned/bilinear_quotient/ops/bqrunner2.sh
directory=/workspace/tensor_language/basis_aligned/bilinear_quotient
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_events_enabled=true
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
