"""POSITIVE CONTROL for the release-D test: does refinement walk away from a dictionary that is
KNOWN to be the true generator?

Motivation. On GPT-2, refining from the SAE feature basis improved HELD-OUT R²(Wx) by +0.024 while
atoms drifted (cos 0.22). Two incompatible readings:

  (H1) reconstruction objectives simply do not select the generating basis  → refinement would
       improve held-out R² even when started from the TRUE dictionary. The test has no power.
  (H2) the test has power, and SAE features are NOT the true generators of GPT-2 activations.

Discriminator. Build data whose generator is known exactly:
      X = D_true C_true + noise,   C_true nonneg k-sparse,   Y = W X
Start refinement AT D_true and measure held-out R²(Wx) with D frozen. If the data really are
generated by D_true + iid noise, D_true is the population optimum, so held-out R² must NOT improve.

  refinement improves held-out from D_true  →  H1 (objective artifact; GPT-2 result means nothing)
  refinement does not improve from D_true   →  H2 (test has power; GPT-2 features aren't generators)

Guards:
  * NOISELESS gate: with noise=0 and OMP k = k_true, round-0 R² must be ~1.0 and refinement must not
    move. If it moves, the harness is broken, not the objective.
  * random-init control must end BELOW true-init (else the setup carries no signal at all).

Run: python -m mechdecomp.refine_power
"""

import torch
import torch.nn.functional as Fn

from .mstep import rowspace_basis
from .release_d import omp_codes

DEV = "cuda"
torch.set_default_dtype(torch.float32)

D_IN, K, KTRUE = 64, 256, 4
NTR, NVA = 8000, 4000
ROUNDS = 8


def make_data(noise, seed=0):
    g = torch.Generator(device="cpu").manual_seed(seed)
    Dt = Fn.normalize(torch.randn(D_IN, K, generator=g), dim=0).to(DEV)
    N = NTR + NVA
    C = torch.zeros(K, N)
    for i in range(N):
        idx = torch.randperm(K, generator=g)[:KTRUE]
        C[idx, i] = torch.rand(KTRUE, generator=g) + 0.5      # nonneg codes
    C = C.to(DEV)
    X = Dt @ C
    X = X + noise * torch.randn(X.shape, generator=g).to(DEV) * X.std()
    W = torch.randn(D_IN, D_IN, generator=g).to(DEV) / D_IN ** 0.5
    return Dt, W, X[:, :NTR].contiguous(), X[:, NTR:].contiguous()


def r2_of(Yh, Y):
    return float(1 - ((Yh - Y) ** 2).sum() / ((Y - Y.mean(1, keepdim=True)) ** 2).sum())


def refine(W, D0, Xtr, Xva, rounds=ROUNDS, k=KTRUE, tag=""):
    Ytr, Yva = W @ Xtr, W @ Xva
    D = D0.clone()
    RS = rowspace_basis(W)
    Wpinv = torch.linalg.pinv(W)
    hist = []
    for rnd in range(rounds):
        WD = W @ D
        C, _ = omp_codes(WD, Ytr, k)
        cs = (D * D0).sum(0)
        WDv = W @ D
        Cv, _ = omp_codes(WDv, Yva, k)
        hist.append((rnd, r2_of(WD @ C, Ytr), r2_of(WDv @ Cv, Yva), float(cs.abs().mean())))
        if rnd == rounds - 1:
            break
        # --- M-step, FIXED: Gauss-Seidel (residual updated in place) + beta re-alternated,
        #     and NO in-loop renormalization (codes are re-solved by OLS next round, so atom
        #     scale is irrelevant to the fit; normalizing with beta frozen breaks optimality).
        E = Ytr - WD @ C
        for j in range(K):
            act = C[j].abs() > 1e-10
            if act.sum() < 2:
                continue
            beta = C[j, act]
            Rj = E[:, act] + torch.outer(WD[:, j], beta)          # remove atom j's contribution
            wd = (Rj @ beta) / (beta @ beta).clamp_min(1e-12)     # optimal Wd_j given beta
            d = RS @ (RS.T @ (Wpinv @ wd))                        # back to input space, in rowspace
            if d.norm() < 1e-8:
                continue
            D[:, j] = d
            wd = W @ d                                            # actual achievable atom
            nb = (wd @ wd).clamp_min(1e-12)
            beta = (Rj.T @ wd) / nb                               # re-alternate beta given wd
            C[j, act] = beta
            WD[:, j] = wd
            E[:, act] = Rj - torch.outer(wd, beta)                # Gauss-Seidel: residual updated
        nrm = D.norm(dim=0).clamp_min(1e-12)                      # normalize AFTER the sweep,
        D = D / nrm                                               # rescaling codes to preserve fit
        C = C * nrm[:, None]
    print(f"  {tag}")
    print("    rnd   train R2   HELD-OUT R2   mean|cos to init|")
    for r, a, b, c in hist:
        print(f"    {r:3d}    {a:7.4f}    {b:8.4f}      {c:.4f}", flush=True)
    return hist


def main():
    # ---------- GUARD: noiseless, true dict ----------
    print("GUARD (noise=0, init=D_true).\n", flush=True)
    Dt, W, Xtr, Xva = make_data(noise=0.0)
    # (a) ORACLE support + OLS: isolates harness error from OMP support-selection error
    Yva = W @ Xva
    Cva_true = torch.linalg.lstsq(Dt, Xva).solution          # exact codes (Dt spans)
    orc = r2_of((W @ Dt) @ Cva_true, Yva)
    assert orc > 0.9999, f"GUARD FAIL: oracle-code R2 {orc:.6f} != 1 — harness broken"
    print(f"  [guard a] oracle codes on D_true: held-out R2 {orc:.6f}  (harness exact)", flush=True)
    # (b) OMP on the same true dictionary: any shortfall is GREEDY SELECTION error, not the dict
    h = refine(W, Dt, Xtr, Xva, rounds=3, tag="noiseless, init = D_true, codes by OMP")
    assert h[0][2] > 0.99, f"GUARD FAIL: OMP on true dict {h[0][2]:.4f} < 0.99"
    assert h[-1][2] - h[0][2] < 0.002, f"GUARD FAIL: refinement moved on noiseless true dict"
    tr = [x[1] for x in h]
    assert all(tr[i+1] >= tr[i] - 1e-4 for i in range(len(tr)-1)), f"GUARD FAIL: train loss not descending {tr}"
    print(f"  [guard b] OMP on D_true {h[0][2]:.4f} vs oracle {orc:.4f}"
          f"  -> greedy-selection error = {orc-h[0][2]:.4f}", flush=True)
    print(f"  [guard c] refinement Δ held-out = {h[-1][2]-h[0][2]:+.4f} (does not move) \n", flush=True)

    # ---------- the discriminating run ----------
    for noise in (0.05, 0.15):
        print(f"===== noise = {noise} =====", flush=True)
        Dt, W, Xtr, Xva = make_data(noise=noise)
        ht = refine(W, Dt, Xtr, Xva, tag=f"init = D_true  (the TRUE generator)")
        g = torch.Generator(device="cpu").manual_seed(1)
        Dr = Fn.normalize(torch.randn(D_IN, K, generator=g), dim=0).to(DEV)
        hr = refine(W, Dr, Xtr, Xva, tag="init = random (control)")
        dt = ht[-1][2] - ht[0][2]
        print(f"\n  Δ held-out R2 from D_true : {dt:+.4f}"
              f"      (H1 if ≫0, H2 if ≈0 or <0)", flush=True)
        print(f"  Δ held-out R2 from random : {hr[-1][2]-hr[0][2]:+.4f}", flush=True)
        print(f"  final held-out: true-init {ht[-1][2]:.4f}   random-init {hr[-1][2]:.4f}\n", flush=True)
    print("DONE", flush=True)


if __name__ == "__main__":
    main()
