#!/usr/bin/env python3
"""CPU audit of low-rank numeric result and its sequence-accounting undercount."""
import ast,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];RUN=ROOT/'basis_aligned/bilinear_quotient/ops/run_numeric_shared_payload_low_rank_v1.py';RESULT=ROOT/'basis_aligned/polynomial_causal/NUMERIC_SHARED_PAYLOAD_LOW_RANK_V1_RESULT.json';OUT=ROOT/'basis_aligned/polynomial_causal/NUMERIC_SHARED_PAYLOAD_LOW_RANK_V1_AUDIT.json'
r=json.loads(RESULT.read_text());ast.parse(RUN.read_text())
fit_e=len(r['fit']['evidence']);test_e=len(r['test']['evidence']);fit_endpoints=32;test_endpoints=128
recomputed=2*fit_endpoints+fit_e+2*test_endpoints+test_e
checks={'terminal_is_cross_authority_null':r['terminal']=='cross_authority_null','instrument_passed':r['predictions']['pred_a_exact_instrument'] is True,'rank_two_selected':r['selected_rank']==2 and r['fit']['rank_pass']=={'fit_list|rank_1':False,'fit_list|rank_2':True,'fit_list|rank_4':True,'fit_list|rank_8':True},'both_test_families_failed':r['test']['rank_pass']=={'copy|rank_2':False,'plus_one|rank_2':False},'evidence_counts_exact':fit_e==160 and test_e==256,'planned_sequences_correct':r['price']['sequences']==736 and recomputed==736,'observed_field_omits_native_batches':r['price']['observed_sequences']==576 and recomputed-r['price']['observed_sequences']==fit_endpoints+test_endpoints,'six_forwards_recorded':r['price']['forwards']==6,'exact_diagnostics_pass':max(r['fit']['diagnostics'][k] for k in ('native_replay_rse','source_sum_rse','cached_decomposition_rse'))<=1e-10 and r['fit']['diagnostics']['installed_error']<=1e-5 and max(r['test']['diagnostics'][k] for k in ('native_replay_rse','source_sum_rse','cached_decomposition_rse'))<=1e-10 and r['test']['diagnostics']['installed_error']<=1e-5}
a={'schema':'numeric_shared_payload_low_rank_v1_audit','result_sha256':hashlib.sha256(RESULT.read_bytes()).hexdigest(),'runner_sha256':hashlib.sha256(RUN.read_bytes()).hexdigest(),'checks':checks,'all_checks_pass':all(checks.values()),'recomputed_execution':{'forwards':6,'sequences':recomputed,'fit_native':fit_endpoints,'fit_capture':fit_endpoints,'fit_patched':fit_e,'test_native':test_endpoints,'test_capture':test_endpoints,'test_patched':test_e},'finding':'Scientific terminal and exact evidence are valid. observed_sequences undercounts by 160 because run_stage returns capture endpoints plus patched rows but omits the separate native_logits endpoints; preregistered and actual total are 736.'}
if not a['all_checks_pass']:raise RuntimeError(a)
OUT.write_text(json.dumps(a,sort_keys=True,separators=(',',':'))+'\n');print(json.dumps(a,indent=2,sort_keys=True))
