"""Commutant probe / simultaneous block-diagonalization of a symmetric family.

Math: the *-algebra generated by symmetric matrices {A_i} admits a canonical
simultaneous block-diagonalization (Artin-Wedderburn); the blocks are the
eigenspace clusters of a generic element of the commutant
C = {X : [X, A_i] = 0 for all i}  (Murota-Kanno-Kojima-Kojima 2010;
Maehara-Murota 2011 error-controlled variant). Blocks are unique up to
orthogonal transforms WITHIN blocks -> any claim at block grain is invariant
under the within-block gauge group by construction.

Intended bilin18 object: the rung-469 family Q(g_c) = sym(Left^T diag(Down^T
g_c) Right) over already-opened task directions g_c. commutant_dim == 1 means
the family generates an algebra with trivial commutant: NO block structure at
any within-block gauge (clean strong null for the gauge-aware route).

Dense implementation, O(n^2) x O(n^2) eigendecomposition: fine to n ~ 60.
For 1152-dim use restrict_family() first (project onto the top-r eigenvectors
of sum A_i^2 -- the task response subspace), then decompose the r x r family.
"""
import numpy as np


def _sym(M):
    return 0.5 * (M + M.T)


def restrict_family(mats, r):
    """Project each A_i onto the span of the top-r eigenvectors of sum A_i^2."""
    S = sum(A @ A for A in mats)
    w, V = np.linalg.eigh(_sym(S))
    U = V[:, np.argsort(w)[::-1][:r]]
    return [U.T @ A @ U for A in mats], U


def commutant_blocks(mats, tol=1e-8, seed=0):
    """Return dict: commutant_dim, block_sizes, basis (orthogonal), off_block_mass.

    off_block_mass: max over A_i of ||off-block part||_F / ||A_i||_F in the
    returned basis -- the error certificate for the decomposition.
    """
    mats = [_sym(np.asarray(A, dtype=float)) for A in mats]
    n = mats[0].shape[0]
    scale = max(np.linalg.norm(A) for A in mats)
    mats = [A / scale for A in mats]
    eye = np.eye(n)
    # L_full = sum K_i^2, K_i = I (x) A_i - A_i (x) I  (symmetric PSD on R^{n^2});
    # kernel(L_full) = commutant of the family.
    L = np.zeros((n * n, n * n))
    for A in mats:
        K = np.kron(eye, A) - np.kron(A, eye)
        L += K @ K
    w, V = np.linalg.eigh(L)
    kernel = V[:, w < tol]
    cdim = kernel.shape[1]
    out = {"commutant_dim": int(cdim), "block_sizes": [n], "basis": eye,
           "off_block_mass": 0.0, "kernel_eigvals": w[: min(6, len(w))].tolist()}
    if cdim <= 1:
        return out  # only identity: irreducible, no split at any gauge
    rng = np.random.default_rng(seed)
    C = None
    for _ in range(8):  # a kernel draw can be antisymmetric; retry
        cand = _sym((kernel @ rng.standard_normal(cdim)).reshape(n, n))
        if np.linalg.norm(cand) > 1e-6:
            C = cand
            break
    if C is None:
        return out
    ew, B = np.linalg.eigh(C)
    # cluster equal eigenvalues (constant within an irreducible block)
    gaps = np.diff(ew)
    cut = max(1e-6, 1e-3 * (ew[-1] - ew[0]))
    sizes, cur = [], 1
    for g in gaps:
        if g > cut:
            sizes.append(cur)
            cur = 1
        else:
            cur += 1
    sizes.append(cur)
    # off-block mass certificate
    idx = np.cumsum([0] + sizes)
    mask = np.zeros((n, n), dtype=bool)
    for a, b in zip(idx[:-1], idx[1:]):
        mask[a:b, a:b] = True
    off = max(np.linalg.norm(np.where(mask, 0.0, B.T @ A @ B)) / np.linalg.norm(A)
              for A in mats)
    out.update(block_sizes=sorted(sizes, reverse=True), basis=B,
               off_block_mass=float(off))
    return out


if __name__ == "__main__":
    rng = np.random.default_rng(7)
    # (a) hidden two-block family (7+5), random orthogonal conjugation
    O = np.linalg.qr(rng.standard_normal((12, 12)))[0]
    fam = []
    for _ in range(4):
        Bk = np.zeros((12, 12))
        Bk[:7, :7] = _sym(rng.standard_normal((7, 7)))
        Bk[7:, 7:] = _sym(rng.standard_normal((5, 5)))
        fam.append(O @ Bk @ O.T)
    r = commutant_blocks(fam)
    print("two-block:", r["commutant_dim"], r["block_sizes"],
          f"off={r['off_block_mass']:.2e}")
    assert r["block_sizes"] == [7, 5] and r["off_block_mass"] < 1e-9
    # (b) generic family: trivial commutant, no split
    g = commutant_blocks([_sym(rng.standard_normal((12, 12))) for _ in range(4)])
    print("generic:", g["commutant_dim"], g["block_sizes"])
    assert g["commutant_dim"] == 1
    # (c) noise robustness: 1e-6 perturbation still splits with small certificate
    noisy = [A + 1e-6 * _sym(rng.standard_normal((12, 12))) for A in fam]
    nz = commutant_blocks(noisy, tol=1e-6)
    print("noisy:", nz["commutant_dim"], nz["block_sizes"],
          f"off={nz['off_block_mass']:.2e}")
    assert nz["block_sizes"] == [7, 5] and nz["off_block_mass"] < 1e-4
    # (d) restriction helper round-trip
    small, U = restrict_family(fam, 12)
    assert commutant_blocks(small)["block_sizes"] == [7, 5]
    print("all commutant.py verifications pass")
