#!/usr/bin/env python3
"""Register the bracket source-factor localization boundary."""
from copy import deepcopy
import json,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[2];POLY=REPO/'basis_aligned/polynomial_causal';BQ=REPO/'basis_aligned/bilinear_quotient';sys.path.insert(0,str(BQ))
from circuit_registry_v2 import _atomic_json,_lock,circuit_path,design_key,execution_key,file_sha256,rebuild_registry_v2,validate_v2
TAG='task.bracket_pending_opener';OLD='pending_opener_state.v38';NEW='pending_opener_state.v39';EVENT='pending_opener.cascade_source_component_factorial.v1.complete.partial_ceiling'
ARTIFACTS={'cascade_source_factorial_v1_prereg':('basis_aligned/polynomial_causal/BRACKET_CASCADE_SOURCE_COMPONENT_FACTORIAL_V1_PREREGISTRATION.md','preregistration'),'cascade_source_factorial_v1_binding':('basis_aligned/polynomial_causal/BRACKET_CASCADE_SOURCE_COMPONENT_FACTORIAL_V1_BINDING.json','binding'),'cascade_source_factorial_v1_runner':('basis_aligned/bilinear_quotient/ops/run_bracket_cascade_source_component_factorial_v1.py','runner'),'cascade_source_factorial_v1_result':('basis_aligned/polynomial_causal/BRACKET_CASCADE_SOURCE_COMPONENT_FACTORIAL_V1_RESULT.json','result'),'cascade_source_factorial_v1_audit':('basis_aligned/polynomial_causal/BRACKET_CASCADE_SOURCE_COMPONENT_FACTORIAL_V1_AUDIT.json','audit')}
def artifact(p,k):return {'path':p,'sha256':file_sha256(REPO/p),'kind':k,'status':'frozen'}
def metric(n,e,b):return {'name':n,'estimate':e,'ci95':None,'bar':b}
def build(path):
 r=json.loads((POLY/'BRACKET_CASCADE_SOURCE_COMPONENT_FACTORIAL_V1_RESULT.json').read_text());a=json.loads((POLY/'BRACKET_CASCADE_SOURCE_COMPONENT_FACTORIAL_V1_AUDIT.json').read_text());assert r['terminal']=='source_factorial_partial_ceiling' and a['all_checks_pass'];record=json.loads(path.read_text());assert record['claims'][-1]['claim_id']==OLD
 for aid,spec in ARTIFACTS.items():record['artifacts'][aid]=artifact(*spec)
 previous=record['claims'][-1];claim=deepcopy(previous);claim.update({'claim_id':NEW,'revision':39,'supersedes':OLD,'evidence_event_ids':[*previous['evidence_event_ids'],EVENT],'next_missing':'The complete seventh-construction source factorial localizes the donor-free miss to accumulated score approximation, dominated by the second multiplicative key factor. Every partial corner passes; both approximate keys with exact payload is the maximally compressed passing ceiling, while the fully donor-free corner alone misses one pair. Three-way interaction is negligible and pairwise terms are small. Improve the architecture-native key2 generator prospectively; do not add suffix interaction, refit payload/key tables, relax bars, or use exact donor components as an executable program.'})
 site={'site_id':'attention13.head8.source_key1_key2_payload_factorial','tensor_path':'query-key1 score times query-key2 score times projected source payload at the pending opener source position','shape':['batch',3],'intervention':'complete exact-donor versus frozen rank-two approximation factorial','ceiling_event_ids':[]};claim['candidate_sites'].append(site);record['claims'].append(claim)
 event={'event_id':EVENT,'claim_id':NEW,'test_type':'composition','stage':'complete','verdict':'held','failure_kind':None,'family_ids':['cascade_pending_stack_top'],'site_id':site['site_id'],'split_plan_id':'pending_opener_seventh_cascade_v1','evaluation_role':'opened_seventh_source_factor_localization','metrics':[metric('selected_corner',r['selected'],'first passing maximally approximated corner'),metric('full_relative_l2',r['overall']['full']['relative_l2_error'],'<=.40 overall and <=.50 each pair'),metric('key12_relative_l2',r['overall']['key12']['relative_l2_error'],'<=.40 overall and <=.50 each pair'),metric('key2_main_error_fraction',a['main_effect_rms_fraction_of_full_error']['key2'],'descriptive localization'),metric('maximum_pairwise_interaction_fraction',max(a['pairwise_interaction_rms_fraction_of_full_error'].values()),'descriptive localization'),metric('three_way_interaction_fraction',a['three_way_interaction_rms_fraction_of_full_error'],'<=.25'),metric('forwards',r['price']['observed_forwards'],'10')],'prereg_artifact_id':'cascade_source_factorial_v1_prereg','result_artifact_id':'cascade_source_factorial_v1_result','input_artifact_ids':list(ARTIFACTS),'seed':None,'checkpoint_sha256':r['checkpoint_sha256'],'supersedes_event_id':None,'replicates_event_id':None,'sections':['basis_aligned/polynomial_causal/BRACKET_CASCADE_SOURCE_COMPONENT_FACTORIAL_V1_PREREGISTRATION.md'],'notes':'Exact donor factors are diagnostic ceilings. Frozen rank-two tables, native recipient query, rows, and bars were unchanged. Zero fits, gradients, updates, gains, or quantization.'};event['design_key']=design_key(record,event);event['execution_key']=execution_key(record,event);record['evidence_events'].append(event);validate_v2(record);return record
def main():
 path=circuit_path(TAG);current=json.loads(path.read_text())
 if any(e['event_id']==EVENT for e in current['evidence_events']):validate_v2(current);rebuild_registry_v2();print('already registered');return
 with _lock('registry'):_atomic_json(path,build(path))
 rebuild_registry_v2();print(json.dumps({'status':'registered','claim_id':NEW,'event_id':EVENT},indent=2))
if __name__=='__main__':main()
