#!/usr/bin/env python3
"""Register the bracket query-context factor2 scalar null."""
from copy import deepcopy
import json,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[2];POLY=REPO/'basis_aligned/polynomial_causal';BQ=REPO/'basis_aligned/bilinear_quotient';sys.path.insert(0,str(BQ))
from circuit_registry_v2 import _atomic_json,_lock,circuit_path,design_key,execution_key,file_sha256,rebuild_registry_v2,validate_v2
TAG='task.bracket_pending_opener';OLD='pending_opener_state.v40';NEW='pending_opener_state.v41';EVENT='pending_opener.key2_query_context_scalar.v1.complete.null'
ARTIFACTS={'key2_context_scalar_v1_prereg':('basis_aligned/polynomial_causal/BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_PREREGISTRATION.md','preregistration'),'key2_context_scalar_v1_binding':('basis_aligned/polynomial_causal/BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_BINDING.json','binding'),'key2_context_scalar_v1_runner':('basis_aligned/bilinear_quotient/ops/run_bracket_key2_query_context_scalar_v1.py','runner'),'key2_context_scalar_v1_result':('basis_aligned/polynomial_causal/BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_RESULT.json','result'),'key2_context_scalar_v1_audit':('basis_aligned/polynomial_causal/BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_AUDIT.json','audit')}
def artifact(p,k):return {'path':p,'sha256':file_sha256(REPO/p),'kind':k,'status':'frozen'}
def metric(n,e,b):return {'name':n,'estimate':e,'ci95':None,'bar':b}
def build(path):
 r=json.loads((POLY/'BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_RESULT.json').read_text());a=json.loads((POLY/'BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_AUDIT.json').read_text());assert r['terminal']=='query_context_scalar_null' and a['all_checks_pass'];record=json.loads(path.read_text());assert record['claims'][-1]['claim_id']==OLD
 for aid,spec in ARTIFACTS.items():record['artifacts'][aid]=artifact(*spec)
 previous=record['claims'][-1];claim=deepcopy(previous);claim.update({'claim_id':NEW,'revision':41,'supersedes':OLD,'evidence_event_ids':[*previous['evidence_event_ids'],EVENT],'next_missing':'Outcome-blind scalar compression of query2-key2 context is also rejected. An anchored one-parameter residual law and a free two-scalar law both worsen exact donor factor2 activation on the seventh construction relative to the absolute type prototype. Together with the full-vector affine null, this closes simple additive recipient-context corrections. Reopen bracket only with an independently derived query-conditioned low-rank adapter or a new native source variable; otherwise move to native generation of the held subject-number axis. Do not tune these coefficients, use behavior in the fit, open the sealed eighth rows, add suffix terms, or quantize.'});site={'site_id':'attention13.head8.key2_query_context_scalar','tensor_path':'absolute donor-type query2-key2 score plus native recipient-minus-recipient-prototype factor2 residual','shape':['batch',2],'intervention':'outcome-blind anchored one-parameter or through-origin two-scalar activation prediction','ceiling_event_ids':[]};claim['candidate_sites'].append(site);record['claims'].append(claim)
 event={'event_id':EVENT,'claim_id':NEW,'test_type':'cross_family_transfer','stage':'complete','verdict':'null','failure_kind':'scientific_null','family_ids':['nested_two_pending_stack_top','triple_pending_stack_top','layered_pending_stack_top','cascade_pending_stack_top'],'site_id':site['site_id'],'split_plan_id':'pending_opener_seventh_cascade_v1','evaluation_role':'first_three_activation_fit_then_seventh_activation_selection','metrics':[metric('absolute_factor2_relative_l2',a['baseline_relative_l2'],'baseline'),metric('anchored_factor2_relative_l2',a['anchored_relative_l2'],'<=.35 and >=.05 improvement'),metric('two_scalar_factor2_relative_l2',a['two_scalar_relative_l2'],'<=.35 and >=.05 improvement'),metric('selected_candidates',0,'>=1'),metric('forwards',r['price']['forwards'],'5'),metric('activation_fits',r['price']['fits'],'2')],'prereg_artifact_id':'key2_context_scalar_v1_prereg','result_artifact_id':'key2_context_scalar_v1_result','input_artifact_ids':list(ARTIFACTS),'seed':None,'checkpoint_sha256':r['checkpoint_sha256'],'supersedes_event_id':None,'replicates_event_id':None,'sections':['basis_aligned/polynomial_causal/BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_PREREGISTRATION.md'],'notes':'Fits used exact factor2 activations only; no behavioral effect or answer logit entered fitting or selection. The sealed eighth construction remained unopened. Zero backwards, updates, gains, or quantization.'};event['design_key']=design_key(record,event);event['execution_key']=execution_key(record,event);record['evidence_events'].append(event);validate_v2(record);return record
def main():
 path=circuit_path(TAG);current=json.loads(path.read_text())
 if any(e['event_id']==EVENT for e in current['evidence_events']):validate_v2(current);rebuild_registry_v2();print('already registered');return
 with _lock('registry'):_atomic_json(path,build(path))
 rebuild_registry_v2();print(json.dumps({'status':'registered','claim_id':NEW,'event_id':EVENT},indent=2))
if __name__=='__main__':main()
