#!/usr/bin/env python3
"""Register the native-relative bracket key transport null."""
from copy import deepcopy
import json,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[2];POLY=REPO/'basis_aligned/polynomial_causal';BQ=REPO/'basis_aligned/bilinear_quotient';sys.path.insert(0,str(BQ))
from circuit_registry_v2 import _atomic_json,_lock,circuit_path,design_key,execution_key,file_sha256,rebuild_registry_v2,validate_v2
TAG='task.bracket_pending_opener';OLD='pending_opener_state.v39';NEW='pending_opener_state.v40';EVENT='pending_opener.key2_native_relative_transport.v1.complete.null'
ARTIFACTS={'serial_rows_builder_v1':('basis_aligned/polynomial_causal/build_bracket_serial_pending_ood_v1_rows.py','builder'),'serial_rows_test_v1':('basis_aligned/polynomial_causal/test_build_bracket_serial_pending_ood_v1_rows.py','test'),'serial_rows_v1':('basis_aligned/polynomial_causal/BRACKET_SERIAL_PENDING_OOD_V1_ROWS.json','rows'),'key2_relative_v1_prereg':('basis_aligned/polynomial_causal/BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_PREREGISTRATION.md','preregistration'),'key2_relative_v1_binding':('basis_aligned/polynomial_causal/BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_BINDING.json','binding'),'key2_relative_v1_runner':('basis_aligned/bilinear_quotient/ops/run_bracket_key2_native_relative_transport_v1.py','runner'),'key2_relative_v1_result':('basis_aligned/polynomial_causal/BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_RESULT.json','result'),'key2_relative_v1_audit':('basis_aligned/polynomial_causal/BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_AUDIT.json','audit')}
def artifact(p,k):return {'path':p,'sha256':file_sha256(REPO/p),'kind':k,'status':'frozen'}
def metric(n,e,b):return {'name':n,'estimate':e,'ci95':None,'bar':b}
def build(path):
 r=json.loads((POLY/'BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_RESULT.json').read_text());a=json.loads((POLY/'BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_AUDIT.json').read_text());assert r['terminal']=='native_relative_key_fit_null' and a['all_checks_pass'];record=json.loads(path.read_text());assert record['claims'][-1]['claim_id']==OLD
 for aid,spec in ARTIFACTS.items():record['artifacts'][aid]=artifact(*spec)
 previous=record['claims'][-1];claim=deepcopy(previous);claim.update({'claim_id':NEW,'revision':40,'supersedes':OLD,'evidence_event_ids':[*previous['evidence_event_ids'],EVENT],'next_missing':'Native-relative key transport is rejected: recipient key plus the frozen type displacement worsens donor-key2 vector fidelity and both relative-key programs fail on the opened seventh construction, so the sealed eighth construction remains unused. The dominant unresolved object is the scalar query2-key2 interaction, not a context-free full key vector. Derive an outcome-blind query-conditioned scalar or low-rank key2 adapter on earlier constructions and require prospective serial-construction transfer; do not retry affine transport, refit failed type tables on seventh rows, add suffix terms, or quantize.'});site={'site_id':'attention13.head8.key2_native_relative_transport','tensor_path':'native recipient pre-rotary normalized key plus frozen donor-minus-recipient delimiter-type displacement','shape':['batch',128],'intervention':'replace absolute rank-two key2 prototype, optionally key1, inside donor-free source program','ceiling_event_ids':[]};claim['candidate_sites'].append(site);record['claims'].append(claim)
 event={'event_id':EVENT,'claim_id':NEW,'test_type':'cross_family_transfer','stage':'complete','verdict':'null','failure_kind':'scientific_null','family_ids':['cascade_pending_stack_top'],'site_id':site['site_id'],'split_plan_id':'pending_opener_seventh_cascade_v1','evaluation_role':'opened_fit_before_conditional_sealed_serial_confirmation','metrics':[metric('key2_vector_relative_l2_improvement',a['key2_relative_l2_improvement'],'>=.05'),metric('relative_key2_behavior_relative_l2',a['relative_key2_behavior_relative_l2'],'<=.40 overall and <=.50 each pair'),metric('relative_both_behavior_relative_l2',a['relative_both_behavior_relative_l2'],'<=.40 overall and <=.50 each pair'),metric('selected_candidates',0,'>=1'),metric('forwards',r['price']['observed_forwards'],'6 FIT-null')],'prereg_artifact_id':'key2_relative_v1_prereg','result_artifact_id':'key2_relative_v1_result','input_artifact_ids':list(ARTIFACTS),'seed':None,'checkpoint_sha256':r['checkpoint_sha256'],'supersedes_event_id':None,'replicates_event_id':None,'sections':['basis_aligned/polynomial_causal/BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_PREREGISTRATION.md'],'notes':'The eighth serial rows were generated and sealed before FIT outcomes but remained unopened because no FIT candidate passed. Zero fits, gradients, updates, gains, or quantization.'};event['design_key']=design_key(record,event);event['execution_key']=execution_key(record,event);record['evidence_events'].append(event);validate_v2(record);return record
def main():
 path=circuit_path(TAG);current=json.loads(path.read_text())
 if any(e['event_id']==EVENT for e in current['evidence_events']):validate_v2(current);rebuild_registry_v2();print('already registered');return
 with _lock('registry'):_atomic_json(path,build(path))
 rebuild_registry_v2();print(json.dumps({'status':'registered','claim_id':NEW,'event_id':EVENT},indent=2))
if __name__=='__main__':main()
