#!/usr/bin/env python3
# BQLANE: gpu
# BQGATE: 6forwards864seq; bracket L13H8 score-payload interaction;0fits0updates.
"""Factor nested-pending L13H8 source edits into score, payload, and interaction."""
from __future__ import annotations
from collections import defaultdict
import hashlib,json,math,os,sys
from pathlib import Path
RUNNER=Path(__file__).resolve(); OPS=RUNNER.parent; ROOT=RUNNER.parents[3]; POLY=ROOT/'basis_aligned/polynomial_causal'
ROWS=POLY/'BRACKET_NESTED_PENDING_OOD_V1_ROWS.json'; CAPABILITY=POLY/'BRACKET_NESTED_PENDING_OOD_CAPABILITY_V1_RESULT.json'; PRIOR=POLY/'BRACKET_NESTED_PENDING_PROGRAM_TRANSFER_V1_RESULT.json'; PREREG=POLY/'BRACKET_NESTED_PENDING_SCORE_PAYLOAD_INTERACTION_V1_PREREGISTRATION.md'; BINDING=POLY/'BRACKET_NESTED_PENDING_SCORE_PAYLOAD_INTERACTION_V1_BINDING.json'; OUT=POLY/'BRACKET_NESTED_PENDING_SCORE_PAYLOAD_INTERACTION_V1_RESULT.json'
BARS={'replay_max':1e-5,'closure_max':1e-5,'pair_positive_min':.90,'additive_cosine_min':.95,'additive_relative_l2_max':.25,'additive_sign_min':.90,'interaction_source_norm_fraction_min':.10,'control_to_target_rms_max':.50}
PREDICTION_REGISTRY={'pred_a_exact_instrument':None,'pred_b_joint_target_live':None,'pred_c_additive_score_payload_sufficient':None,'pred_d_material_score_payload_interaction':None,'pred_e_control_selectivity':None}
def digest(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def vector_metrics(actual,predicted):
 dot=sum(a*b for a,b in zip(actual,predicted)); an=math.sqrt(sum(a*a for a in actual)); pn=math.sqrt(sum(p*p for p in predicted)); return {'count':len(actual),'cosine':dot/max(an*pn,1e-30),'relative_l2_error':math.sqrt(sum((a-p)**2 for a,p in zip(actual,predicted)))/max(an,1e-30),'sign_agreement':sum((a>0)==(p>0) for a,p in zip(actual,predicted))/len(actual),'predicted_to_actual_norm_ratio':pn/max(an,1e-30)}
def main():
 binding=json.loads(BINDING.read_text()); paths={'rows':ROWS,'capability':CAPABILITY,'prior_result':PRIOR,'preregistration':PREREG}; assert all(digest(paths[k])==v for k,v in binding['files'].items()); frozen=json.loads(ROWS.read_text()); capability=json.loads(CAPABILITY.read_text()); assert capability['terminal']=='capability_pass' and binding['bars']==BARS and binding['price']=={'forwards':6,'sequences':864}
 if os.environ.get('BQLIB_DRYRUN')=='1' and os.environ.get('BQLIB_NO_MODEL')=='1' and os.environ.get('EXPECTED_SHA256'):
  print(json.dumps({'dryrun':True,'model_loaded':False,'gpu_accessed':False,'rows':frozen['row_count'],'endpoints':frozen['endpoint_count'],'arms':['native','replay','score','payload','joint','additive'],'bars':BARS,'price':binding['price'],'predicates':list(PREDICTION_REGISTRY)},sort_keys=True)); return
 assert not OUT.exists(); sys.path.insert(0,str(OPS)); import torch; import run_bracket_l13h8_source_region_payload_factorial as exact; from circuit_fast_screen_managed_runner import atomic_create_json; torch.set_num_threads(2); tm,F,facade=exact._dependencies(); model,checkpoint=facade.load_bilin18(device='cuda',dtype=torch.float32,verify_weights_sha256=True); rows=frozen['rows']; endpoints=[(r,s) for r in rows for s in ('base','donor')]; length=max(len(r[f'{s}_ids']) for r,s in endpoints); tokens=torch.full((len(endpoints),length),50256,dtype=torch.long,device='cuda'); finals=[]; sources=[]
 for i,(row,side) in enumerate(endpoints):
  ids=row[f'{side}_ids']; tokens[i,:len(ids)]=torch.tensor(ids,device='cuda'); finals.append(len(ids)-1); sources.append(row[f'{side}_open_position'])
 finals_t=torch.tensor(finals,device='cuda'); sources_t=torch.tensor(sources,device='cuda'); ar=torch.arange(len(endpoints),device='cuda'); counts=[0,0]
 def count(_m,args,_o): counts[0]+=1; counts[1]+=len(args[0])
 handle=model.transformer.h[0].attn.register_forward_hook(count)
 try:
  with torch.inference_mode():
   native=exact.native_logits(model,tokens,tm,F); replay,factors=exact.factor_forward(model,tokens,finals_t,{},tm,F,facade); pr=factors['p'][ar,sources_t]; ur=factors['u'][ar,sources_t]; donor=ar^1; pd=factors['p'][donor,sources_t[donor]]; ud=factors['u'][donor,sources_t[donor]]; self_term=pr[:,None]*ur; score_term=pd[:,None]*ur; payload_term=pr[:,None]*ud; joint_term=pd[:,None]*ud; additive_term=score_term+payload_term-self_term; interaction_term=(pd-pr)[:,None]*(ud-ur); source_closure=float((joint_term-additive_term-interaction_term).abs().max()); replacements={'score':score_term,'payload':payload_term,'joint':joint_term,'additive':additive_term}; arms={name:exact.factor_forward(model,tokens,finals_t,{},tm,F,facade,replacement_terms=value,source_positions=sources_t)[0] for name,value in replacements.items()}
 finally: handle.remove()
 replay_error=max(float((native[i,finals[i]]-replay[i,finals[i]]).abs().max()) for i in range(len(endpoints))); records=[]
 for i,(row,side) in enumerate(endpoints):
  other='donor' if side=='base' else 'base'; pair=f"{int(row[f'{side}_answer_id'])}->{int(row[f'{other}_answer_id'])}"; direction='base_to_donor' if side=='base' else 'donor_to_base'; rec={'row_id':row['row_id'],'side':side,'program_role':row['program_role'],'ordered_pair':pair}
  if row['program_role']=='target':
   for name in replacements: rec[name+'_effect']=float(exact.endpoint_change(replay[i,finals[i]],arms[name][i,finals[i]],row,direction))
  else:
   answer=int(row[f'{side}_answer_id']); base=float(exact.closer_margin(replay[i,finals[i]],answer)); rec['control_changes']={name:float(exact.closer_margin(arms[name][i,finals[i]],answer)-base) for name in replacements}
  records.append(rec)
 targets=[r for r in records if r['program_role']=='target']; controls=[r for r in records if r['program_role']=='control']; joint=[r['joint_effect'] for r in targets]; additive=[r['additive_effect'] for r in targets]; score=[r['score_effect'] for r in targets]; payload=[r['payload_effect'] for r in targets]; behavioral_interaction=[j-s-p for j,s,p in zip(joint,score,payload)]; additive_metrics=vector_metrics(joint,additive); by_pair={pair:{'n':sum(r['ordered_pair']==pair for r in targets),'joint_positive_fraction':sum(r['joint_effect']>0 for r in targets if r['ordered_pair']==pair)/12,'additive':vector_metrics([r['joint_effect'] for r in targets if r['ordered_pair']==pair],[r['additive_effect'] for r in targets if r['ordered_pair']==pair])} for pair in sorted({r['ordered_pair'] for r in targets})}; source_joint_norm=float(joint_term[[i for i,(r,s) in enumerate(endpoints) if r['program_role']=='target']].double().norm()); source_delta_norm=float((joint_term-self_term)[[i for i,(r,s) in enumerate(endpoints) if r['program_role']=='target']].double().norm()); source_interaction_norm=float(interaction_term[[i for i,(r,s) in enumerate(endpoints) if r['program_role']=='target']].double().norm()); interaction_fraction=source_interaction_norm/max(source_delta_norm,1e-30); target_rms=math.sqrt(sum(x*x for x in joint)/len(joint)); control_rms={name:math.sqrt(sum(r['control_changes'][name]**2 for r in controls)/len(controls)) for name in replacements}; max_control_ratio=max(v/max(target_rms,1e-30) for v in control_rms.values()); instrument=counts==[6,864] and replay_error<=BARS['replay_max'] and source_closure<=BARS['closure_max'] and len(targets)==len(controls)==72; live=all(v['joint_positive_fraction']>=BARS['pair_positive_min'] for v in by_pair.values()); additive_ok=additive_metrics['cosine']>=BARS['additive_cosine_min'] and additive_metrics['relative_l2_error']<=BARS['additive_relative_l2_max'] and additive_metrics['sign_agreement']>=BARS['additive_sign_min']; interaction_material=interaction_fraction>=BARS['interaction_source_norm_fraction_min'] and additive_metrics['relative_l2_error']>BARS['additive_relative_l2_max']; selective=max_control_ratio<=BARS['control_to_target_rms_max']; predictions={'pred_a_exact_instrument':bool(instrument),'pred_b_joint_target_live':bool(instrument and live),'pred_c_additive_score_payload_sufficient':bool(instrument and additive_ok),'pred_d_material_score_payload_interaction':bool(instrument and interaction_material),'pred_e_control_selectivity':bool(instrument and selective)}
 if not instrument or not live: terminal='invalid_or_dead_parent'
 elif additive_ok and selective: terminal='additive_score_payload_factorization'
 elif interaction_material and selective: terminal='score_payload_interaction_required'
 else: terminal='mixed_or_nonselective'
 result={'schema':'bracket_nested_pending_score_payload_interaction_v1_result','terminal':terminal,'predictions':predictions,'instrument':{'native_factor_replay_max_logit_error':replay_error,'source_term_closure_max_absolute_error':source_closure},'overall':{'additive_vs_joint':additive_metrics,'source_interaction_over_joint_delta_norm':interaction_fraction,'source_joint_term_norm':source_joint_norm,'target_joint_effect_rms':target_rms,'behavioral_interaction_over_joint_norm':math.sqrt(sum(x*x for x in behavioral_interaction))/max(math.sqrt(sum(x*x for x in joint)),1e-30)},'by_ordered_pair':by_pair,'control_rms':control_rms,'maximum_control_to_target_joint_rms':max_control_ratio,'price':{'forwards':counts[0],'sequences':counts[1],'fits':0,'backwards':0,'updates':0},'claim_boundary':'Opened nested-authority exact L13H8 source-term factorial through native suffix; no universal vector, gain refit, autonomous generator, fresh confirmation, or quantization.','rows_sha256':digest(ROWS),'binding_sha256':digest(BINDING),'runner_sha256':digest(RUNNER),'checkpoint_sha256':checkpoint.weights_sha256,'records':records}; atomic_create_json(OUT,result); print(json.dumps({k:result[k] for k in ('terminal','predictions','instrument','overall','control_rms','maximum_control_to_target_joint_rms','price')},indent=2)); assert instrument
if __name__=='__main__': main()
