#!/usr/bin/env python3
# BQLANE: gpu
# BQGATE: EXPERIMENT pred_a_exact_factor_instrument pred_b_anchored_scalar_transfers pred_c_two_scalar_transfers pred_d_query_context_scalar_selected
"""Fit and select an outcome-blind query-context scalar for bracket key2."""
from __future__ import annotations
import hashlib,json,math,os,signal,sys,time
from pathlib import Path
RUNNER=Path(__file__).resolve();OPS=RUNNER.parent;ROOT=RUNNER.parents[3];POLY=ROOT/'basis_aligned/polynomial_causal'
TRAIN=(POLY/'BRACKET_NESTED_PENDING_OOD_V1_ROWS.json',POLY/'BRACKET_TRIPLE_PENDING_OOD_V1_ROWS.json',POLY/'BRACKET_LAYERED_PENDING_OOD_V1_ROWS.json');FIT=POLY/'BRACKET_CASCADE_PENDING_OOD_V1_ROWS.json';PROGRAM=POLY/'BRACKET_LAYERED_PENDING_KEY_RANK2_INTERACTION_V1_RESULT.json';PREREG=POLY/'BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_PREREGISTRATION.md';BINDING=POLY/'BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_BINDING.json';OUT=POLY/'BRACKET_KEY2_QUERY_CONTEXT_SCALAR_V1_RESULT.json'
TYPES=('parenthesis','square','quote');HEAD=8;D=128;PRICE={'forwards':5,'sequences':720,'fits':2,'backwards':0,'updates':0};BARS={'replay_max':1e-5,'improvement_min':.05,'cosine_min':.95,'relative_l2_max':.35,'sign_min':.90,'norm_min':.70,'norm_max':1.30};CANDIDATES=('anchored','two_scalar')
PREDICTION_REGISTRY={'pred_a_exact_factor_instrument':None,'pred_b_anchored_scalar_transfers':None,'pred_c_two_scalar_transfers':None,'pred_d_query_context_scalar_selected':None}
def digest(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def metrics(a,b):
 a=[float(x) for x in a];b=[float(x) for x in b];an=math.sqrt(sum(x*x for x in a));bn=math.sqrt(sum(x*x for x in b));return {'count':len(a),'cosine':sum(x*y for x,y in zip(a,b))/max(an*bn,1e-30),'relative_l2_error':math.sqrt(sum((x-y)**2 for x,y in zip(a,b)))/max(an,1e-30),'sign_agreement':sum((x>0)==(y>0) for x,y in zip(a,b))/len(a),'predicted_to_actual_norm_ratio':bn/max(an,1e-30)}
def passed(v,baseline):return baseline['relative_l2_error']-v['relative_l2_error']>=BARS['improvement_min'] and v['cosine']>=BARS['cosine_min'] and v['relative_l2_error']<=BARS['relative_l2_max'] and v['sign_agreement']>=BARS['sign_min'] and BARS['norm_min']<=v['predicted_to_actual_norm_ratio']<=BARS['norm_max']
def load_bound():
 b=json.loads(BINDING.read_text());paths={'train_nested':TRAIN[0],'train_triple':TRAIN[1],'train_layered':TRAIN[2],'fit':FIT,'program':PROGRAM,'preregistration':PREREG};assert all(digest(paths[k])==v for k,v in b['files'].items());assert b['bars']==BARS and b['price']==PRICE and b['candidates']==list(CANDIDATES);panels=[json.loads(p.read_text()) for p in (*TRAIN,FIT)];program=json.loads(PROGRAM.read_text());assert all(x['endpoint_count']==144 for x in panels) and program['terminal']=='key_rank2_payload_rank2_interaction_transfer';return panels,program
def plan():
 panels,program=load_bound();return {'schema':'bracket_key2_query_context_scalar_v1_plan','model_loaded':False,'gpu_accessed':False,'queue_touched':False,'train_endpoints':sum(x['endpoint_count'] for x in panels[:3]),'fit_endpoints':panels[3]['endpoint_count'],'candidates':list(CANDIDATES),'program_rank':program['program']['key2']['rank'],'bars':BARS,'price':PRICE,'predicates':list(PREDICTION_REGISTRY)}
def main():
 panels,program_result=load_bound();sys.path.insert(0,str(OPS));from circuit_exactness_preflight import managed_execution_mode,validate_literal_prediction_registry,validate_result_contract;validate_literal_prediction_registry(RUNNER.read_text(),PREDICTION_REGISTRY)
 if managed_execution_mode(os.environ)=='preflight':print(json.dumps(plan(),sort_keys=True));return
 assert not OUT.exists();signal.alarm(600);import torch;import run_bracket_l13h8_source_region_payload_factorial as exact;from circuit_fast_screen_managed_runner import atomic_create_json
 torch.set_num_threads(2);tm,F,facade=exact._dependencies();model,checkpoint=facade.load_bilin18(device='cuda',dtype=torch.float32,verify_weights_sha256=True);table={k:torch.tensor(v,dtype=torch.float64,device='cuda') if isinstance(v,list) else v for k,v in program_result['program']['key2'].items()};counts=[0,0];absolute=[];context=[];target=[];split=[];replay_errors=[]
 def count(_m,args,_o):counts[0]+=1;counts[1]+=len(args[0])
 handle=model.transformer.h[0].attn.register_forward_hook(count);tic=time.perf_counter()
 try:
  for panel_index,panel in enumerate(panels):
   tag='fit' if panel_index==3 else f'train{panel_index}';tagged=[(r,s) for r in panel['rows'] for s in ('base','donor')];length=max(len(r[f'{side}_ids']) for r,side in tagged);tokens=torch.full((len(tagged),length),50256,dtype=torch.long,device='cuda');finals=[];sources=[]
   for i,(row,side) in enumerate(tagged):ids=row[f'{side}_ids'];tokens[i,:len(ids)]=torch.tensor(ids,device='cuda');finals.append(len(ids)-1);sources.append(row[f'{side}_open_position'])
   finals_t=torch.tensor(finals,device='cuda');sources_t=torch.tensor(sources,device='cuda');ar=torch.arange(len(tagged),device='cuda');captured={}
   def capture(event):
    if event.site!=13:return event.block.attn(event.state,event.first_value)
    state,first,attn=event.state,event.first_value,event.block.attn;batch,seq,width=state.shape;heads=9;q=exact._linear(state,attn.c_q.weight,F).view(batch,seq,heads,D);k=exact._linear(state,attn.c_k.weight,F).view(batch,seq,heads,D);q2=exact._linear(state,attn.c_q2.weight,F).view(batch,seq,heads,D);k2=exact._linear(state,attn.c_k2.weight,F).view(batch,seq,heads,D);raw=exact._linear(state,attn.c_v.weight,F).view(batch,seq,heads,D);value=(1-attn.lamb)*raw+attn.lamb*first.view_as(raw);cos,sin=attn.rotary(q);rotate=sys.modules[type(attn).__module__].apply_rotary_emb;qr=rotate(F.rms_norm(q,(D,)),cos,sin);kr=rotate(F.rms_norm(k,(D,)),cos,sin);q2r=rotate(F.rms_norm(q2,(D,)),cos,sin);k2n=F.rms_norm(k2,(D,));k2r=rotate(k2n,cos,sin);s1=torch.einsum('bqhd,bkhd->bhqk',qr,kr)/D;s2=torch.einsum('bqhd,bkhd->bhqk',q2r,k2r)/D;pattern=(s1*s2).masked_fill(~torch.tril(torch.ones(seq,seq,dtype=torch.bool,device=state.device)),0);all_heads=torch.einsum('bhqk,bkhd->bhqd',pattern,value);write=exact._linear(all_heads.transpose(1,2).contiguous().view(batch,seq,width),attn.c_proj.weight,F);captured.update({'q2':q2r[ar,finals_t,HEAD].detach(),'b':s2[ar,HEAD,finals_t,sources_t].float().detach(),'cos':cos.detach(),'sin':sin.detach(),'rotate':rotate});return write,first
   with torch.inference_mode():
    native=exact.native_logits(model,tokens,tm,F).cpu() if tag=='fit' else None;replay_gpu=facade.forward_with_dispatch(model,tokens,capture,lambda e:e.block.mlp(e.state),require_production=False).float();replay=replay_gpu.cpu() if tag=='fit' else None;del replay_gpu
   if tag=='fit':replay_errors.append(max(float((native[i,finals[i]]-replay[i,finals[i]]).abs().max()) for i in range(len(tagged))));del native,replay
   for i,(row,side) in enumerate(tagged):
    if row['program_role']!='target':continue
    other='donor' if side=='base' else 'base';rt=row[f'{side}_type'];dt=row[f'{other}_type'];ri,di=TYPES.index(rt),TYPES.index(dt);proto_r=table['mean']+table['type_coefficients'][ri]@table['basis'];proto_d=table['mean']+table['type_coefficients'][di]@table['basis'];cos=captured['cos'][0,sources_t[i],0][None,None,:];sin=captured['sin'][0,sources_t[i],0][None,None,:];rotate=captured['rotate'];pr=rotate(proto_r.to(torch.float32)[None,None,:],cos,sin)[0,0];pd=rotate(proto_d.to(torch.float32)[None,None,:],cos,sin)[0,0];q=captured['q2'][i];absolute.append(float((q*pd).sum()/D));prototype_recipient=float((q*pr).sum()/D);context.append(float(captured['b'][i])-prototype_recipient);target.append(float(captured['b'][i^1]));split.append(tag)
   del tokens,captured;torch.cuda.empty_cache()
 finally:handle.remove()
 replay_error=max(replay_errors)
 train=[i for i,s in enumerate(split) if s!='fit'];fit=[i for i,s in enumerate(split) if s=='fit'];A=torch.tensor([absolute[i] for i in train],dtype=torch.float64);C=torch.tensor([context[i] for i in train],dtype=torch.float64);Y=torch.tensor([target[i] for i in train],dtype=torch.float64);gamma=float(torch.linalg.lstsq(C[:,None],(Y-A)[:,None]).solution[0,0]);coef=torch.linalg.lstsq(torch.stack((A,C),1),Y[:,None]).solution[:,0];programs={'anchored':{'coefficients':[1.0,gamma],'parameter_count':1},'two_scalar':{'coefficients':coef.tolist(),'parameter_count':2}};actual=[target[i] for i in fit];baseline=metrics(actual,[absolute[i] for i in fit]);reports={}
 for name,p in programs.items():alpha,g=p['coefficients'];pred=[alpha*absolute[i]+g*context[i] for i in fit];v=metrics(actual,pred);reports[name]={'metrics':v,'relative_l2_improvement':baseline['relative_l2_error']-v['relative_l2_error'],'passes':passed(v,baseline)}
 selected=next((n for n in CANDIDATES if reports[n]['passes']),None);instrument=counts==[PRICE['forwards'],PRICE['sequences']] and replay_error<=BARS['replay_max'] and len(train)==216 and len(fit)==72 and program_result['program']['key2']['rank']==2;pred={'pred_a_exact_factor_instrument':bool(instrument),'pred_b_anchored_scalar_transfers':bool(instrument and reports['anchored']['passes']),'pred_c_two_scalar_transfers':bool(instrument and reports['two_scalar']['passes']),'pred_d_query_context_scalar_selected':bool(instrument and selected)};terminal='invalid' if not instrument else 'query_context_scalar_selected' if selected else 'query_context_scalar_null';result={'schema':'bracket_key2_query_context_scalar_v1_result','terminal':terminal,'predictions':pred,'selected':selected,'programs':programs,'absolute_fit_metrics':baseline,'candidate_reports':reports,'instrument':{'replay_max_logit_error':replay_error,'train_target_endpoints':len(train),'fit_target_endpoints':len(fit)},'price':PRICE,'fits':2,'backwards':0,'updates':0,'quantized':False,'checkpoint_sha256':checkpoint.weights_sha256,'runner_sha256':digest(RUNNER),'binding_sha256':digest(BINDING),'wall_seconds':time.perf_counter()-tic};validate_result_contract(result,PREDICTION_REGISTRY);atomic_create_json(OUT,result);print(json.dumps({k:result[k] for k in ('terminal','predictions','selected','programs','absolute_fit_metrics','candidate_reports','instrument','price')},indent=2));assert terminal!='invalid'
if __name__=='__main__':main()
