#!/usr/bin/env python3
# BQGATE: EXPERIMENT pred_a_bilinear_closure pred_b_top_pair_involves_head_8_1 pred_c_pairs_with_8_1_carry_half pred_d_8_1_self_term_at_least_020
"""Aspectual has/had definition-of-done battery, step 16: FOLD MLP8's bank write into writer-pair terms.

Lane: Claude circuit lane. Library: `aspectual_dod_lib.py`. Parents: v13 (MLP8 writes ~28% of the bank
states heads 9.1/9.4 read on their reader direction), v14/v15 (attention8's part is head 8.1's token-only
cue read).

WHY. MLP8 is bilinear: mlp8(s) = Down((L x)(R x)) + bias with x = rms_norm(x_8[s]), and x_8[s] is an exact
lambda-weighted sum of writers (embedding, attn:00..07, mlp:00..07, and attention8 split into its nine
per-head writes O_h z_h). So r_h . mlp8(s) expands EXACTLY into writer-pair terms
   T[a,b] = sum_j (Down^T r_h)_j (L C_a)_j (R C_b)_j / rho^2,   rho = rms(x_8[s]),
plus the bias (cancels in the since-by contrast). better_circuits §3.5/§3.9: keep the products, keep the
context slot explicit -- no averaging over prompts before the contrast. If the dominant pairs are
8.1 x 8.1 or 8.1 x embedding, MLP8's bank contribution is also generated by 8.1's cue read and the bank
closes to token-only inputs up to MLP6/7. Evidence tag: fold, opened rows.

PREDICTIONS (scored as written; failures preserved)
    pred_a_bilinear_closure           sum over all pairs + bias equals r_h . mlp8(s) from the trace within
                                      relative 1e-3 at every row and bank position, both reader heads
    pred_b_top_pair_involves_head_8_1 for both reader heads the largest |symmetrized pair share| of the
                                      oriented contrast has attnhead:08:1 as at least one factor
    pred_c_pairs_with_8_1_carry_half  pairs with 8.1 as at least one factor carry >= 0.50 of the contrast
    pred_d_8_1_self_term_at_least_020 the 8.1 x 8.1 term alone carries >= 0.20. Prior: unsure.

PRICE (registered maximum): 2 batches x 1 trace forward = 2 forwards; all pair terms on captured vectors;
0 backwards; 0 fits. Bar <= 6.
"""
from __future__ import annotations

from datetime import datetime, timezone
import json
import os
import time
from pathlib import Path

import aspectual_dod_lib as L
import circuit_fast_screen_producer as producer
import run_aspectual_dod_removal_v1 as v1

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "circuits/followups/aspectual_anchor_dod_mlp8_pair_fold_v16_result.json"
CANDIDATE_ID = "aspectual_anchor.has_vs_had.dod_mlp8_pair_fold_v16"
TOKENS = {"has": 468, "had": 550}
CLOSURE_TOL, HALF, SELF_MIN = 1e-3, 0.50, 0.20
FORWARDS_MAX = 6
COMP = L.Component("attn9_h1_h4_final", 9, "attn", (1, 4), "final")
WRITERS = ["embed"] + [f"{k}:{l:02d}" for l in range(8) for k in ("attn", "mlp")] + [f"attnhead:08:{h}" for h in range(9)]


def _plan(rows):
    return {"candidate_id": CANDIDATE_ID, "rows": len(rows), "rows_sha256": L.rows_sha256(rows), "writers": WRITERS,
            "pairs": len(WRITERS) ** 2, "forwards_max": FORWARDS_MAX, "model_backwards": 0, "model_updates": 0,
            "fit_parameters": 0, "gpu_accessed": False, "model_loaded": False, "execution_policy": "managed_queue_only",
            "bars": {"closure_tol": CLOSURE_TOL, "half": HALF, "self_min": SELF_MIN}}


def writers_at_block8_input(tr, pos):
    """Exact writer decomposition of x_8[pos] = live_8 + attn8 (attn8 split by head)."""
    x0 = tr[("embed", pos)]
    C = {"embed": x0.clone()}
    for l in range(8):
        l0, l1 = tr[f"lambda0:{l:02d}"], tr[f"lambda1:{l:02d}"]
        for k in C:
            C[k] = l0 * C[k]
        C["embed"] = C["embed"] + l1 * x0
        C[f"attn:{l:02d}"] = tr[(f"attn:{l:02d}", pos)].clone()
        C[f"mlp:{l:02d}"] = tr[(f"mlp:{l:02d}", pos)].clone()
    l0, l1 = tr["lambda0:08"], tr["lambda1:08"]
    for k in C:
        C[k] = l0 * C[k]
    C["embed"] = C["embed"] + l1 * x0
    for h in range(9):
        C[f"attnhead:08:{h}"] = tr[(f"attnhead:08:{h}", pos)].clone()
    return C


def main() -> None:
    rows = L.build_rows()
    if L.rows_sha256(rows) != v1.EXPECTED_ROWS_SHA256:
        raise SystemExit("rows changed; refusing to run against an unregistered panel")
    if os.environ.get("BQLIB_DRYRUN") or os.environ.get("BQLIB_NO_MODEL"):
        print(json.dumps(_plan(rows), indent=2, sort_keys=True)); return
    t0 = time.perf_counter()
    backend = producer.Bilin18TorchBackend.load("cuda")
    torch, model = backend.torch, backend.model
    fw = L.ManualForward(backend)
    fw.directions = L.readout_directions(model, (COMP,), TOKENS["has"], TOKENS["had"])
    readers = L.reader_directions(model, COMP, fw.directions)
    mlp8 = model.transformer.h[8].mlp
    Lw, Rw, Dw = mlp8.Left.weight.detach().float(), mlp8.Right.weight.detach().float(), mlp8.Down.weight.detach().float()
    bias = mlp8.Down_bias.detach().float()
    forwards = 0
    traces = []
    for start in range(0, len(rows), v1.BATCH):
        chunk = rows[start:start + v1.BATCH]
        traces.extend(L.forward_trace_positions(fw, chunk, lambda r: r.source_positions, upto_layer=9, head_write_layers=(8,))); forwards += 1
    closure_max = 0.0
    n = len(WRITERS)
    pair_tables = {rh: [] for rh in COMP.heads}   # per row: dict pos -> n x n tensor
    for row, tr in zip(rows, traces):
        for rh in COMP.heads:
            r = readers[rh].to(Dw.device)
            u = Dw.T @ r                                        # (4608,)
            per_pos = {}
            for pos in row.source_positions:
                C = writers_at_block8_input(tr, pos)
                x8 = sum(C.values())
                rho = float(x8.pow(2).mean().sqrt())
                M = torch.stack([C[w] for w in WRITERS]).to(Dw.device)          # (n, 1152)
                LA, RB = M @ Lw.T, M @ Rw.T                                     # (n, 4608)
                T = ((LA * u) @ RB.T) / (rho * rho)                              # (n, n)
                total = float(T.sum() + r @ bias)
                true = float(r @ tr[("mlp:08", pos)].to(Dw.device))
                closure_max = max(closure_max, abs(total - true) / max(abs(true), 1e-6))
                per_pos[pos] = T.cpu()
            pair_tables[rh].append(per_pos)
    partner = L.partner_of(rows)
    report = {}
    for rh in COMP.heads:
        acc = torch.zeros(n, n)
        for i, row in enumerate(rows):
            if not row.present:
                continue
            j = rows.index(partner[row.row_id])
            for k, pos in enumerate(row.source_positions):
                acc += pair_tables[rh][i][pos] - pair_tables[rh][j][rows[j].source_positions[k]]
        contrast = float(acc.sum())
        sym = (acc + acc.T) / 2
        shares = {}
        for a in range(n):
            for b in range(a, n):
                v = float(sym[a, b] * (1 if a == b else 2)) / contrast
                shares[f"{WRITERS[a]} x {WRITERS[b]}"] = v
        ranked = sorted(shares, key=lambda k: -abs(shares[k]))
        with_81 = sum(v for k, v in shares.items() if "attnhead:08:1" in k.split(" x "))
        self_81 = shares["attnhead:08:1 x attnhead:08:1"]
        report[f"9.{rh}"] = {"contrast": contrast, "top10": [(k, shares[k]) for k in ranked[:10]], "pairs_with_8_1_share": with_81,
                             "self_8_1_share": self_81, "top_pair": ranked[0]}
        print(f"9.{rh}", "contrast", round(contrast, 2), "with_8.1", round(with_81, 3), "self", round(self_81, 3), "top", [(k, round(v, 3)) for k, v in report[f"9.{rh}"]["top10"][:6]])
    predictions = {
        "pred_a_bilinear_closure": closure_max <= CLOSURE_TOL,
        "pred_b_top_pair_involves_head_8_1": all("attnhead:08:1" in r["top_pair"].split(" x ") for r in report.values()),
        "pred_c_pairs_with_8_1_carry_half": all(r["pairs_with_8_1_share"] >= HALF for r in report.values()),
        "pred_d_8_1_self_term_at_least_020": all(r["self_8_1_share"] >= SELF_MIN for r in report.values()),
    }
    if forwards > FORWARDS_MAX:
        raise SystemExit(f"price exceeded: {forwards} > {FORWARDS_MAX}")
    result = {"schema": "aspectual_anchor_dod_mlp8_pair_fold_result_v16", "candidate_id": CANDIDATE_ID, "plan": _plan(rows),
              "closure_max_relative_error": closure_max, "readers": report, "predictions": predictions, "forwards": forwards,
              "serial_seconds": time.perf_counter() - t0, "finished_utc": datetime.now(timezone.utc).isoformat()}
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"predictions": predictions, "closure": closure_max, "forwards": forwards}, indent=2))


if __name__ == "__main__":
    main()
