#!/usr/bin/env python3
# BQLANE: gpu
# BQGATE: EXPERIMENT pred_a_exact_instrument_and_capability pred_b_key2_transport_improves pred_c_fit_program_selected pred_d_fresh_program_transfers pred_e_control_selectivity
"""Select and confirm donor-free native-relative bracket key transport."""
from __future__ import annotations
from collections import defaultdict
import hashlib,json,math,os,signal,sys,time
from pathlib import Path

RUNNER=Path(__file__).resolve();OPS=RUNNER.parent;ROOT=RUNNER.parents[3];POLY=ROOT/'basis_aligned/polynomial_causal'
FIT_ROWS=POLY/'BRACKET_CASCADE_PENDING_OOD_V1_ROWS.json';SELECT_ROWS=POLY/'BRACKET_SERIAL_PENDING_OOD_V1_ROWS.json';BUILDER=POLY/'build_bracket_serial_pending_ood_v1_rows.py';PROGRAM=POLY/'BRACKET_LAYERED_PENDING_KEY_RANK2_INTERACTION_V1_RESULT.json';FACTORIAL=POLY/'BRACKET_CASCADE_SOURCE_COMPONENT_FACTORIAL_V1_RESULT.json';PREREG=POLY/'BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_PREREGISTRATION.md';BINDING=POLY/'BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_BINDING.json';OUT=POLY/'BRACKET_KEY2_NATIVE_RELATIVE_TRANSPORT_V1_RESULT.json'
TYPES=('parenthesis','square','quote');HEAD=8;D=128;CANDIDATES=('relative_key2','relative_both');PRICE={'maximum_forwards':11,'maximum_sequences':1584,'null_forwards':6,'null_sequences':864,'fits':0,'backwards':0,'updates':0}
BARS={'replay_max':1e-5,'capability_accuracy_min':.75,'exact_positive_min':.90,'key2_relative_l2_improvement_min':.05,'prediction_cosine_min':.90,'prediction_relative_l2_max':.40,'prediction_sign_min':.90,'prediction_norm_min':.60,'prediction_norm_max':1.40,'pair_cosine_min':.75,'pair_relative_l2_max':.50,'pair_sign_min':.85,'control_to_target_rms_max':.50}
PREDICTION_REGISTRY={'pred_a_exact_instrument_and_capability':None,'pred_b_key2_transport_improves':None,'pred_c_fit_program_selected':None,'pred_d_fresh_program_transfers':None,'pred_e_control_selectivity':None}
def digest(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def canonical(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def metrics(a,b):
 a=[float(x) for x in a];b=[float(x) for x in b];an=math.sqrt(sum(x*x for x in a));bn=math.sqrt(sum(x*x for x in b));return {'count':len(a),'cosine':sum(x*y for x,y in zip(a,b))/max(an*bn,1e-30),'relative_l2_error':math.sqrt(sum((x-y)**2 for x,y in zip(a,b)))/max(an,1e-30),'sign_agreement':sum((x>0)==(y>0) for x,y in zip(a,b))/len(a),'predicted_to_actual_norm_ratio':bn/max(an,1e-30)}
def metric_pass(v,pair=False):return v['cosine']>=BARS['pair_cosine_min' if pair else 'prediction_cosine_min'] and v['relative_l2_error']<=BARS['pair_relative_l2_max' if pair else 'prediction_relative_l2_max'] and v['sign_agreement']>=BARS['pair_sign_min' if pair else 'prediction_sign_min'] and (pair or BARS['prediction_norm_min']<=v['predicted_to_actual_norm_ratio']<=BARS['prediction_norm_max'])
def load_bound():
 b=json.loads(BINDING.read_text());paths={'fit_rows':FIT_ROWS,'select_rows':SELECT_ROWS,'builder':BUILDER,'program':PROGRAM,'factorial':FACTORIAL,'preregistration':PREREG};assert all(digest(paths[k])==v for k,v in b['files'].items());assert b['bars']==BARS and b['price']==PRICE and b['candidates']==list(CANDIDATES);fit=json.loads(FIT_ROWS.read_text());select=json.loads(SELECT_ROWS.read_text());assert canonical(fit['rows'])==fit['row_manifest_sha256'] and canonical(select['rows'])==select['row_manifest_sha256'];program=json.loads(PROGRAM.read_text());factorial=json.loads(FACTORIAL.read_text());assert program['terminal']=='key_rank2_payload_rank2_interaction_transfer' and factorial['terminal']=='source_factorial_partial_ceiling';return fit,select,program
def plan():
 fit,select,program=load_bound();return {'schema':'bracket_key2_native_relative_transport_v1_plan','model_loaded':False,'gpu_accessed':False,'queue_touched':False,'fit_endpoints':fit['endpoint_count'],'select_endpoints':select['endpoint_count'],'candidates':list(CANDIDATES),'program_ranks':{k:v['rank'] for k,v in program['program'].items()},'bars':BARS,'price':PRICE,'predicates':list(PREDICTION_REGISTRY)}
def main():
 fit,select,program_result=load_bound();sys.path.insert(0,str(OPS));from circuit_exactness_preflight import managed_execution_mode,validate_literal_prediction_registry,validate_result_contract;validate_literal_prediction_registry(RUNNER.read_text(),PREDICTION_REGISTRY)
 if managed_execution_mode(os.environ)=='preflight':print(json.dumps(plan(),sort_keys=True));return
 assert not OUT.exists();signal.alarm(600);import torch;import run_bracket_l13h8_source_region_payload_factorial as exact;from circuit_fast_screen_managed_runner import atomic_create_json
 torch.set_num_threads(2);tm,F,facade=exact._dependencies();model,checkpoint=facade.load_bilin18(device='cuda',dtype=torch.float32,verify_weights_sha256=True);counts=[0,0]
 def count(_m,args,_o):counts[0]+=1;counts[1]+=len(args[0])
 handle=model.transformer.h[0].attn.register_forward_hook(count);tic=time.perf_counter()
 def execute_panel(frozen,candidates):
  before=tuple(counts);rows=frozen['rows'];endpoints=[(r,s) for r in rows for s in ('base','donor')];length=max(len(r[f'{s}_ids']) for r,s in endpoints);tokens=torch.full((len(endpoints),length),50256,dtype=torch.long,device='cuda');finals=[];sources=[]
  for i,(row,side) in enumerate(endpoints):ids=row[f'{side}_ids'];tokens[i,:len(ids)]=torch.tensor(ids,device='cuda');finals.append(len(ids)-1);sources.append(row[f'{side}_open_position'])
  finals_t=torch.tensor(finals,device='cuda');sources_t=torch.tensor(sources,device='cuda');ar=torch.arange(len(endpoints),device='cuda')
  with torch.inference_mode():native=exact.native_logits(model,tokens,tm,F).cpu()
  captured={}
  def capture(event):
   if event.site!=13:return event.block.attn(event.state,event.first_value)
   state,first,attn=event.state,event.first_value,event.block.attn;batch,seq,width=state.shape;heads=9;q=exact._linear(state,attn.c_q.weight,F).view(batch,seq,heads,D);k=exact._linear(state,attn.c_k.weight,F).view(batch,seq,heads,D);q2=exact._linear(state,attn.c_q2.weight,F).view(batch,seq,heads,D);k2=exact._linear(state,attn.c_k2.weight,F).view(batch,seq,heads,D);raw=exact._linear(state,attn.c_v.weight,F).view(batch,seq,heads,D);value=(1-attn.lamb)*raw+attn.lamb*first.view_as(raw);cos,sin=attn.rotary(q);rotate=sys.modules[type(attn).__module__].apply_rotary_emb;qn,kn=F.rms_norm(q,(D,)),F.rms_norm(k,(D,));q2n,k2n=F.rms_norm(q2,(D,)),F.rms_norm(k2,(D,));qr,kr=rotate(qn,cos,sin),rotate(kn,cos,sin);q2r,k2r=rotate(q2n,cos,sin),rotate(k2n,cos,sin);s1=torch.einsum('bqhd,bkhd->bhqk',qr,kr)/D;s2=torch.einsum('bqhd,bkhd->bhqk',q2r,k2r)/D;pattern=(s1*s2).masked_fill(~torch.tril(torch.ones(seq,seq,dtype=torch.bool,device=state.device)),0);all_heads=torch.einsum('bhqk,bkhd->bhqd',pattern,value);write=exact._linear(all_heads.transpose(1,2).contiguous().view(batch,seq,width),attn.c_proj.weight,F);weight=attn.c_proj.weight[:,HEAD*D:(HEAD+1)*D];u=exact._linear(value[:,:,HEAD].float(),weight.float(),F);captured.update({'p':pattern[ar,HEAD,finals_t].float().detach(),'u':u.detach(),'q1':qr[ar,finals_t,HEAD].detach(),'q2':q2r[ar,finals_t,HEAD].detach(),'key1':kn[ar,sources_t,HEAD].detach(),'key2':k2n[ar,sources_t,HEAD].detach(),'cos':cos.detach(),'sin':sin.detach(),'rotate':rotate});return write,first
  with torch.inference_mode():replay_gpu=facade.forward_with_dispatch(model,tokens,capture,lambda e:e.block.mlp(e.state),require_production=False).float();replay=replay_gpu.cpu();del replay_gpu;torch.cuda.empty_cache()
  p=captured['p'][ar,sources_t];u=captured['u'][ar,sources_t];donor=ar^1;pd=p[donor];ud=u[donor];tables={n:{k:torch.tensor(v,dtype=torch.float64,device='cuda') if isinstance(v,list) else v for k,v in t.items()} for n,t in program_result['program'].items()};du=torch.zeros_like(u);absolute={n:torch.zeros((len(endpoints),D),device='cuda') for n in ('key1','key2')};relative={n:torch.zeros((len(endpoints),D),device='cuda') for n in ('key1','key2')}
  for i,(row,side) in enumerate(endpoints):
   if row['program_role']=='target':other='donor' if side=='base' else 'base';rt=row[f'{side}_type'];dt=row[f'{other}_type']
   else:rt=dt=row['inner_type']
   ri,di=TYPES.index(rt),TYPES.index(dt);tab=tables['payload'];du[i]=((tab['type_coefficients'][di]-tab['type_coefficients'][ri])@tab['basis']).to(u.dtype)
   for n in ('key1','key2'):
    tab=tables[n];proto_r=tab['mean']+tab['type_coefficients'][ri]@tab['basis'];proto_d=tab['mean']+tab['type_coefficients'][di]@tab['basis'];absolute[n][i]=proto_d.to(absolute[n].dtype);relative[n][i]=(captured[n][i]+(proto_d-proto_r).to(captured[n].dtype))
  cos=captured['cos'][0,sources_t,0][:,None,None,:];sin=captured['sin'][0,sources_t,0][:,None,None,:];rotate=captured['rotate']
  def factor(n,key):return (captured[n]*rotate(key[:,None,None,:],cos,sin)[:,0,0]).sum(-1)/D
  a_abs=factor('q1',absolute['key1']);b_abs=factor('q2',absolute['key2']);a_rel=factor('q1',relative['key1']);b_rel=factor('q2',relative['key2']);uh=u+du;replacements={'exact':pd[:,None]*ud,'absolute_full':(a_abs*b_abs)[:,None]*uh,'relative_key2':(a_abs*b_rel)[:,None]*uh,'relative_both':(a_rel*b_rel)[:,None]*uh};outputs={}
  for name in ('exact','absolute_full',*candidates):logits,unused=exact.factor_forward(model,tokens,finals_t,{},tm,F,facade,replacement_terms=replacements[name],source_positions=sources_t);outputs[name]=logits.cpu();del logits,unused;torch.cuda.empty_cache()
  records=[];caps=defaultdict(list);vec={'actual':[],'absolute':[],'relative':[]}
  for i,(row,side) in enumerate(endpoints):
   answer=int(row[f'{side}_answer_id']);other='donor' if side=='base' else 'base';oa=int(row[f'{other}_answer_id']);caps[(row['program_role'],answer,side if row['program_role']=='control' else oa)].append(float(exact.closer_margin(native[i,finals[i]],answer)));rec={'row_id':row['row_id'],'side':side,'program_role':row['program_role'],'ordered_pair':f'{answer}->{oa}'}
   if row['program_role']=='target':
    direction='base_to_donor' if side=='base' else 'donor_to_base'
    for name in outputs:rec[name+'_effect']=float(exact.endpoint_change(replay[i,finals[i]],outputs[name][i,finals[i]],row,direction))
    vec['actual'].extend(captured['k2'][donor[i]].double().cpu().tolist());vec['absolute'].extend(absolute['key2'][i].double().cpu().tolist());vec['relative'].extend(relative['key2'][i].double().cpu().tolist())
   else:
    base=float(exact.closer_margin(replay[i,finals[i]],answer));rec['control_changes']={name:float(exact.closer_margin(outputs[name][i,finals[i]],answer)-base) for name in outputs if name!='exact'}
   records.append(rec)
  target=[r for r in records if r['program_role']=='target'];control=[r for r in records if r['program_role']=='control'];pairs=sorted({r['ordered_pair'] for r in target});target_rms=math.sqrt(sum(r['exact_effect']**2 for r in target)/len(target));reports={}
  for name in ('absolute_full',*candidates):
   overall=metrics([r['exact_effect'] for r in target],[r[name+'_effect'] for r in target]);by_pair={p:metrics([r['exact_effect'] for r in target if r['ordered_pair']==p],[r[name+'_effect'] for r in target if r['ordered_pair']==p]) for p in pairs};cf=math.sqrt(sum(r['control_changes'][name]**2 for r in control)/len(control))/max(target_rms,1e-30);reports[name]={'overall':overall,'by_pair':by_pair,'control_to_target_rms':cf,'passes':bool(metric_pass(overall) and all(metric_pass(v,True) for v in by_pair.values()) and cf<=BARS['control_to_target_rms_max'])}
  key2={'absolute':metrics(vec['actual'],vec['absolute']),'relative':metrics(vec['actual'],vec['relative'])};improvement=key2['absolute']['relative_l2_error']-key2['relative']['relative_l2_error'];capable=all(sum(x>0 for x in v)/len(v)>=BARS['capability_accuracy_min'] and sum(v)/len(v)>0 for v in caps.values());replay_error=max(float((native[i,finals[i]]-replay[i,finals[i]]).abs().max()) for i in range(len(endpoints)));local=(counts[0]-before[0],counts[1]-before[1]);instrument=local==(4+len(candidates),(4+len(candidates))*144) and replay_error<=BARS['replay_max'] and capable and set(t['rank'] for t in program_result['program'].values())=={2};parent=all(sum(r['exact_effect']>0 for r in target if r['ordered_pair']==p)/sum(r['ordered_pair']==p for r in target)>=BARS['exact_positive_min'] for p in pairs);return {'instrument':instrument,'parent_live':parent,'local_price':local,'replay_error':replay_error,'key2_metrics':key2,'key2_relative_l2_improvement':improvement,'reports':reports,'records':records}
 try:
  fit_result=execute_panel(fit,CANDIDATES);selected=next((n for n in CANDIDATES if fit_result['instrument'] and fit_result['parent_live'] and fit_result['key2_relative_l2_improvement']>=BARS['key2_relative_l2_improvement_min'] and fit_result['reports'][n]['passes']),None);select_result=execute_panel(select,(selected,)) if selected else None
 finally:handle.remove()
 expected=(PRICE['maximum_forwards'],PRICE['maximum_sequences']) if selected else (PRICE['null_forwards'],PRICE['null_sequences']);instrument=tuple(counts)==expected and fit_result['instrument'] and (select_result is None or select_result['instrument']);improves=fit_result['key2_relative_l2_improvement']>=BARS['key2_relative_l2_improvement_min'];transfer=bool(selected and select_result['parent_live'] and select_result['key2_relative_l2_improvement']>=BARS['key2_relative_l2_improvement_min'] and select_result['reports'][selected]['passes']);selective=bool(selected and fit_result['reports'][selected]['control_to_target_rms']<=BARS['control_to_target_rms_max'] and select_result['reports'][selected]['control_to_target_rms']<=BARS['control_to_target_rms_max']);pred={'pred_a_exact_instrument_and_capability':bool(instrument),'pred_b_key2_transport_improves':bool(instrument and improves),'pred_c_fit_program_selected':bool(instrument and selected),'pred_d_fresh_program_transfers':bool(instrument and transfer),'pred_e_control_selectivity':bool(instrument and selective)};terminal='invalid' if not instrument else 'native_relative_key_transport' if transfer else 'native_relative_key_fit_null' if not selected else 'native_relative_key_transfer_null';result={'schema':'bracket_key2_native_relative_transport_v1_result','terminal':terminal,'predictions':pred,'selected':selected,'fit':fit_result,'select':select_result,'price':{**PRICE,'observed_forwards':counts[0],'observed_sequences':counts[1]},'fits':0,'backwards':0,'updates':0,'quantized':False,'checkpoint_sha256':checkpoint.weights_sha256,'runner_sha256':digest(RUNNER),'binding_sha256':digest(BINDING),'wall_seconds':time.perf_counter()-tic};validate_result_contract(result,PREDICTION_REGISTRY);atomic_create_json(OUT,result);print(json.dumps({'terminal':terminal,'predictions':pred,'selected':selected,'fit_key2':fit_result['key2_metrics'],'fit_reports':fit_result['reports'],'select_key2':None if select_result is None else select_result['key2_metrics'],'select_reports':None if select_result is None else select_result['reports'],'price':result['price']},indent=2));assert terminal!='invalid'
if __name__=='__main__':main()
