import json
from pathlib import Path
import torch
from arithmetic_dag import DAG
from quadratic_student_fit import gram
P=Path(__file__).resolve().parent

def main():
 torch.set_num_threads(2);torch.set_default_dtype(torch.float64);core=torch.load(P/'CENTERED_QUADRATIC_CAPACITY_V1.pt',weights_only=True);source=torch.load(P/'NATIVE_CENTERED_COMPACT_V1.pt',weights_only=True);s={k:v.double() for k,v in source['students'][core['source_key']].items()};panels=torch.load(P/'NATIVE_QUARTIC_COVARIANCE_V1.pt',weights_only=True)['panels'];targets=torch.load(P/'NATIVE_VARIATION_AUDIT_V1.pt',weights_only=True)['targets'];T=core['core'].flatten(1);left,sigma,_=torch.linalg.svd(T,full_matrices=False);norm=T.square().sum();A,B,C=[core[k] for k in ['A','B','C']];G=gram(A,B);tr=(A*B).sum(1);originalmean=s['constant']+core['output_frame']@(C@tr);rows=[];exports={}
 for rank in [2,3,4,6]:
  W=core['output_frame']@left[:,:rank];Z=left[:,:rank].T@C;writer=W@Z;constant=originalmean-writer@tr;approx=left[:,:rank]@(left[:,:rank].T@T);retention=1-float((approx-T).square().sum()/norm);bound=float(sigma[:rank].square().sum()/norm);assert abs(retention-bound)<1e-10;primitive=float((writer.square().sum(0)*G.diag()).sum()/((writer@G)*writer).sum());component=float(((Z@G)*Z).sum()/approx.square().sum());assert abs(component-1)<1e-10;program=dict(mu=s['mu'],constant=constant,linear_writer=s['linear_writer'],linear_reader=s['linear_reader'],quadratic_left=s['quadratic_left'],quadratic_right=s['quadratic_right'],W=W,Z=Z);price=sum(v.numel() for v in program.values());assert price==39168+1160*rank;errors=[];variations=[]
  for panel,y in zip(panels,targets):
   delta=panel['rows'].double()-s['mu'];q=(delta@s['quadratic_left'].T)*(delta@s['quadratic_right'].T);prediction=constant+(delta@s['linear_reader'].T)@s['linear_writer'].T+q@Z.T@W.T;errors.append(float((prediction-y).norm()/y.norm()));variations.append(float(((prediction-prediction.mean(0))-(y-y.mean(0))).norm()/(y-y.mean(0)).norm()))
  d=DAG(degree_limit=2);one=d.constant();delta=[d.linear([(d.input(i),1),(one,-float(v))]) for i,v in enumerate(s['mu'])];lin=[d.linear(zip(delta,row.tolist())) for row in s['linear_reader']];q=[d.product(d.linear(zip(delta,a.tolist())),d.linear(zip(delta,b.tolist()))) for a,b in zip(s['quadratic_left'],s['quadratic_right'])];h=[d.linear(zip(q,row.tolist())) for row in Z];outputs=[d.linear(list(zip(lin,l.tolist()))+list(zip(h,w.tolist()))+[(one,float(c))]) for l,w,c in zip(s['linear_writer'],W,constant)];x=panels[0]['rows'][:32].double();delta0=x-s['mu'];expected=constant+(delta0@s['linear_reader'].T)@s['linear_writer'].T+((delta0@s['quadratic_left'].T)*(delta0@s['quadratic_right'].T))@Z.T@W.T;replay=float((d.evaluate(outputs,x)-expected).norm()/expected.norm());assert replay<1e-10 and d.cost(outputs)['stored_coefficients']==price;rows.append(dict(rank=rank,products=8,scalar_count=price,retained_quadratic_energy=retention,full_quartic_errors=errors,centered_variation_errors=variations,output_component_energy_ratio=component,primitive_component_energy_ratio=primitive,graph_cost=d.cost(outputs),graph_replay=replay));exports[rank]={k:v.float() for k,v in program.items()};print(rows[-1],flush=True)
 four=next(r for r in rows if r['rank']==4);result=dict(records=rows,singular_values=sigma.tolist(),predictions=dict(pred_a=all(r['graph_replay']<1e-10 for r in rows),pred_b=abs(four['full_quartic_errors'][1]-.231228871375852)<.01,pred_c=four['primitive_component_energy_ratio']<10),scope='Closed-form outputsharing baseline withoriginal8products globallyreused. Allranks declared; no empiricalselection or semantics.');(P/'CENTERED_OUTPUT_BLOCK_V1.json').write_text(json.dumps(result,indent=2)+'\n');torch.save(dict(programs=exports,teacher_scale=source['teacher_scale']),P/'CENTERED_OUTPUT_BLOCK_V1.pt')
if __name__=='__main__':main()
