"""Exact small-core representation and necessary output-rank bounds."""
import json
from pathlib import Path
import torch
P=Path(__file__).resolve().parent

def main():
 torch.set_num_threads(4);torch.set_default_dtype(torch.float64);source=torch.load(P/'NATIVE_CENTERED_COMPACT_V1.pt',weights_only=True);key=('centered_floor01',8,8,'muon',1);s={k:v.double() for k,v in source['students'][key].items()};panel=torch.load(P/'NATIVE_QUARTIC_COVARIANCE_V1.pt',weights_only=True)['panels'][0];M=panel['covariance'].double();M=(M+M.T)/2;ev,V=torch.linalg.eigh(M);L=(V*ev.clamp_min(.01*float(M.trace()/1152)).sqrt())@V.T;A,B,C=[s[k] for k in ['quadratic_left','quadratic_right','quadratic_writer']];stack=torch.cat([A,B]);Pinput,R=torch.linalg.qr((stack@L).T);Qout,Csmall=torch.linalg.qr(C);a,b=A@L@Pinput,B@L@Pinput;core=.5*(torch.einsum('vk,ki,kj->vij',Csmall,a,b)+torch.einsum('vk,kj,ki->vij',Csmall,a,b));sv=torch.linalg.svdvals(core.flatten(1));energy=sv.square().sum();ceilings=(sv.square().cumsum(0)/energy).tolist();mapback=torch.linalg.solve(R.T,stack);replay=float((mapback@L-Pinput.T).norm()/Pinput.norm());assert replay<1e-10;assert float((core-core.transpose(1,2)).norm())<1e-10*float(core.norm());result=dict(source_key=list(key),core_shape=list(core.shape),weighted_quadratic_energy=float(energy),output_rank_retention_upper_bounds=ceilings,mapback_relative_error=replay,reader_basis_condition=float(torch.linalg.cond(R)),scope='Necessary quadratic-output rank bound on frozen centered student under original covariance metric. k scalar quadratic products with linear output readout imply output rank<=k. Bound is optimistic, not proof of attainable CP rank or a bound on arbitrary higher-degree approximants.');(P/'CENTERED_QUADRATIC_CAPACITY_V1.json').write_text(json.dumps(result,indent=2)+'\n');torch.save(dict(core=core,C=Csmall,A=a,B=b,input_mapback=mapback,output_frame=Qout,source_key=key),P/'CENTERED_QUADRATIC_CAPACITY_V1.pt');print(result)
if __name__=='__main__':main()
