import itertools,json
from pathlib import Path
import torch
from shared_quadratic_bank import normalize_bank,bank_gram,native_bank_cross,roots,bank_entries
from implicit_quartic import entries
P=Path(__file__).resolve().parent;torch.set_num_threads(1);torch.set_default_dtype(torch.float64);torch.manual_seed(1749);d=6;rawU=torch.randn(3,2,d,requires_grad=True);rawV=torch.randn(3,2,d,requires_grad=True);U,V=normalize_bank(rawU,rawV);Q=(U.transpose(-1,-2)@V+V.transpose(-1,-2)@U)/2;i,j=roots(len(U),U.device);A=Q[i];B=Q[j];dense=(torch.einsum('aij,akl->aijkl',A,B)+torch.einsum('aij,akl->aijkl',B,A)+torch.einsum('aik,ajl->aijkl',A,B)+torch.einsum('aik,ajl->aijkl',B,A)+torch.einsum('ail,ajk->aijkl',A,B)+torch.einsum('ail,ajk->aijkl',B,A))/6;G=bank_gram(U,V);Gref=dense.flatten(1)@dense.flatten(1).T;teacher=[torch.randn(*shape) for shape in [(3,4),(4,5),(4,5),(5,7),(7,d),(7,d)]];idx=torch.tensor(list(itertools.product(range(d),repeat=4)));H=entries(*teacher,idx).T;cross=native_bank_cross(teacher,U,V);ref=H@dense.flatten(1).T;value=max(float(((G-Gref).norm()/Gref.norm()).detach()),float(((cross-ref).norm()/ref.norm()).detach()));g=torch.autograd.grad(G.square().sum()+cross.square().sum(),[rawU,rawV],retain_graph=True);h=torch.autograd.grad(Gref.square().sum()+ref.square().sum(),[rawU,rawV]);grad=max(float((a-b).norm()/b.norm()) for a,b in zip(g,h));norm=float((Q.flatten(1).norm(dim=1)-1).abs().max().detach());assert max(value,grad,norm)<1e-11
entry_error=float(((bank_entries(U,V,idx)-dense.flatten(1).T).norm()/dense.norm()).detach());assert entry_error<1e-11
out=dict(entry_relative_error=entry_error,value_relative_error=value,gradient_relative_error=grad,quadratic_norm_error=norm,scope='Shared low-rank quadratic dictionary, all unordered root products. Exact small-factor self Gram and native teacher cross, independently dense-validated including normalization gradients. No optimization/native recovery claim.')
(P/'SHARED_QUADRATIC_BANK_CHECK_V1.json').write_text(json.dumps(out,indent=2)+'\n');print(out)
