from pathlib import Path
import torch,json,time
p=Path('/workspace/tensor_language/basis_aligned/polynomial_causal/direct_tensor_match');torch.set_num_threads(2);torch.set_grad_enabled(False);start=time.perf_counter();rows=torch.load(p/'MIDPOINT_CALIBRATION_ROWS_V1.pt',weights_only=True);n=rows['n'].flatten(0,1).double();m=rows['m'].flatten(0,1).double();old=torch.load(p/'MIDPOINT_EXTRACTED_PROGRAM_V1.pt',weights_only=True);source=torch.load(p/'MIDPOINT_CENTERED_BLOCK_PROGRAM_V1.pt',weights_only=True);K=torch.load(p/'MIDPOINT_FACTOR_PROGRAMS_V1.pt',weights_only=True)['K'].double();M=torch.load(p/'MIDPOINT_TIED_READERS_V1.pt',weights_only=True)['common_moment'];e,V=torch.linalg.eigh(M+1e-6*M.trace()/1152*torch.eye(1152));S=(V*e.sqrt()[None,:])@V.T;I=(V*e.rsqrt()[None,:])@V.T;curves=[];directions=[];offset=[];widths=[]
for g,k in enumerate(K):
 z=S@k@S;vals,U=torch.linalg.eigh((z+z.T)/2)
 for sign in [1,-1]:
  ids=torch.where(vals*sign>0)[0];ids=ids[vals[ids].abs().argsort(descending=True)];v=(I@U[:,ids])*vals[ids].abs().sqrt()[None,:];truth=((n@v)*(m@v)).sum(1);truth-=truth.mean();terms=(n@v[:,:16])*(m@v[:,:16]);pred=terms.cumsum(1);pred-=pred.mean(0);errors=((pred-truth[:,None]).square().sum(0)/truth.square().sum()).sqrt();eligible=[r for r in range(3,17) if float(errors[r-1])<=.1];width=min(eligible) if eligible else 16;index=2*g+(0 if sign==1 else 1);widths.append(width);directions.append(v[:,:width]);raw=terms[:,:width].sum(1);offset.append(raw.mean());curves.append(dict(block=index,rank_errors={str(r):float(errors[r-1]) for r in range(1,17)},selected_width=width,calibration_target_met=bool(eligible)))
D=torch.cat(directions,dim=1);readout=torch.zeros(sum(widths),8,dtype=torch.float64);at=0
for g,w in enumerate(widths):readout[at:at+w,g]=1;at+=w
program=dict(directions=D.float(),readout=readout.float(),offset=torch.stack(offset).float(),reduced_writers=source['program']['reduced_writers']);source['program']=program;source['scope']='Adaptive3:16 eigenwidth perblock, chosen byoriginalcalibration centerederror<=.1. Reuseddiagnosticselection, noheldfit. Teacher8blocks unchanged.';out=p/'MIDPOINT_ADAPTIVE_BLOCKS_V1.json';assert not out.exists();result=dict(widths=widths,products=sum(widths),input_coefficients=1152*sum(widths),projection_multiplications=2*1152*sum(widths),curves=curves,all_calibration_targets_met=all(x['calibration_target_met'] for x in curves),seconds=time.perf_counter()-start,scope=source['scope']);out.write_text(json.dumps(result,indent=2)+'\n');torch.save(source,p/'MIDPOINT_ADAPTIVE_BLOCKS_PROGRAM_V1.pt');print(json.dumps({k:v for k,v in result.items() if k!='curves'},indent=2))
