"""Full head8.2 fields generated by the frozen residual6 formula."""
import torch
import torch.nn.functional as F
from attention7 import execute as attention7
from readers import execute as readers

def from_projected(projected,first_values,head):
    q1,k1,q2,k2,value=projected.double().split(128,-1);t=projected.shape[1];eps=torch.finfo(torch.float32).eps
    inv=1/(10000**(torch.arange(0,128,2,dtype=torch.float32,device=projected.device)/128));angles=torch.outer(torch.arange(t,dtype=torch.float32,device=projected.device),inv)
    co,si=angles.cos().bfloat16().double(),angles.sin().bfloat16().double()
    def rotate(x):
        x=x/(x.square().mean(-1,keepdim=True)+eps).sqrt();a,b=x.chunk(2,-1)
        return torch.cat([a*co+b*si,-a*si+b*co],-1)
    return {**{n:rotate(x) for n,x in zip(['q1','k1','q2','k2'],[q1,k1,q2,k2])},'value':(1-head['mixture'].double())*value+head['mixture'].double()*first_values[...,256:384].double()}

def execute(program,residual6,token_ids):
    g=attention7(program['attention7'],residual6,token_ids);other=g['other_sources'].double()
    rho=(other.square().mean(-1,keepdim=True)+torch.finfo(torch.float32).eps).sqrt()
    projected=(F.linear(other,program['head8']['sources'].double())+program['attention7']['lambdas8'][0].double()*readers(program['readers'],g['normalized_mlp7']).double())/rho
    return from_projected(projected,g['first_values'],program['head8'])

def city_write(recipient,source,head,city,destination):
    route=((recipient['q1']*source['k1'][:,city,None]).sum(-1)/128)*((recipient['q2']*source['k2'][:,city,None]).sum(-1)/128)
    support=destination & (torch.arange(route.shape[1],device=route.device)>=city)
    return F.linear(route[...,None]*source['value'][:,city,None],head['output'].double())*support[None,:,None]

def interchange(program,recipient_residual6,recipient_tokens,donor_residual6,donor_tokens,city,destination):
    recipient=execute(program,recipient_residual6,recipient_tokens);donor=execute(program,donor_residual6,donor_tokens)
    return city_write(recipient,donor,program['head8'],city,destination)-city_write(recipient,recipient,program['head8'],city,destination)
