"""Generate CIRCUITS_INDEX.md from the canonical registry.

Only records explicitly present in ``circuits/registry.json`` are rendered; aggregate
JSON artifacts in the directory are never guessed to be circuits from their filename.
"""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CIRCUITS = ROOT / "circuits"
REGISTRY = CIRCUITS / "registry.json"
OUT = ROOT / "CIRCUITS_INDEX.md"


def load_record(file_name):
    return json.loads((CIRCUITS / file_name).read_text())


def legacy_row(tag, registry_row, document):
    story = document.get("story", {})
    verdict = ""
    agents = set()
    for certification in document.get("certification", []):
        if isinstance(certification, dict):
            if certification.get("test") == "reviewer-two" or certification.get("gate") == "reviewer-two":
                verdict = certification.get("verdict", "")
            agent = certification.get("agent") or certification.get("source")
            if agent:
                agents.add(str(agent))
    provenance = document.get("provenance", {})
    if provenance.get("agent"):
        agents.add(provenance["agent"])
    return {
        "tag": tag,
        "kind": "census_slice",
        "instance": document.get("tree", {}).get("instance", "?"),
        "status": verdict or "legacy",
        "variable": (story.get("blind_name") or "")[:60],
        "families": "—",
        "negative": "—",
        "active_negative": "—",
        "latest_event": "—",
        "next": "see circuit record",
        "agents": ",".join(sorted(agents))[:40],
    }


def v2_row(tag, registry_row, document):
    active_id = registry_row["active_claim_id"]
    claim = next(item for item in document["claims"] if item["claim_id"] == active_id)
    family_count = len(claim["counterfactual_families"])
    return {
        "tag": tag,
        "kind": registry_row["kind"],
        "instance": registry_row.get("identity_instance") or "task-defined",
        "status": registry_row["claim_status"],
        "variable": registry_row["causal_variable_id"],
        "families": str(family_count),
        "negative": str(registry_row["negative_event_count"]),
        "active_negative": str(registry_row.get("active_negative_event_count", registry_row["negative_event_count"])),
        "latest_event": registry_row.get("latest_active_event") or "—",
        "next": claim.get("next_missing", ""),
        "agents": "",
    }


def main():
    registry = json.loads(REGISTRY.read_text())["circuits"]
    rows = []
    for tag, registry_row in registry.items():
        document = load_record(registry_row["file"])
        if registry_row.get("schema_version") == 2:
            rows.append(v2_row(tag, registry_row, document))
        else:
            rows.append(legacy_row(tag, registry_row, document))
    kind_order = {"behavior_circuit": 0, "shared_subroutine": 1, "census_slice": 2}
    rows.sort(key=lambda row: (kind_order.get(row["kind"], 3), row["tag"]))
    n_behavior = sum(row["kind"] == "behavior_circuit" for row in rows)
    n_subroutine = sum(row["kind"] == "shared_subroutine" for row in rows)
    lines = [
        "# Circuit index (generated by make_circuit_index.py — do not edit)",
        "",
        f"{len(rows)} canonical records: {n_behavior} behavior circuits, {n_subroutine} shared "
        f"subroutine{'s' if n_subroutine != 1 else ''}, "
        f"and {len(rows)-n_behavior-n_subroutine} legacy census records.",
        "Negative/invalid results are counted as evidence, not omitted. Check this view and then the linked JSON record before opening work.",
        "",
        "| circuit | kind | identity | status | causal variable / legacy story | CF families | active / historical negative events | latest active evidence | exact next missing evidence |",
        "|---|---|---|---|---|---:|---:|---|---|",
    ]
    for row in rows:
        next_step = row["next"].replace("|", "/")
        variable = row["variable"].replace("|", "/")
        lines.append(
            f"| `{row['tag']}` | {row['kind']} | {row['instance']} | {row['status']} | "
            f"{variable} | {row['families']} | {row['active_negative']} / {row['negative']} | "
            f"{row['latest_event']} | {next_step} |"
        )
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.name}: {len(rows)} records, {n_behavior} behavior circuits")


if __name__ == "__main__":
    main()
