"""Generate CIRCUITS_INDEX.md -- the at-a-glance table over every
circuit record. CPU-only; consolidator (driver wake loop) reruns
it after each wave and commits alongside the records. Columns:
tag, tree, concentration, program bacc, story (truncated), flags,
reviewer verdict, agents. Sorted: diverse tree first, then by
reviewer status, then tag."""
import json, os, glob
PT='/workspace/tensor_language/basis_aligned/bilinear_quotient/'

def one(fn):
    try: d=json.load(open(fn))
    except Exception: return None
    tag=d.get('tag') or os.path.basename(fn)[:-5]
    tree=d.get('tree',{}).get('instance','?')
    causal=d.get('causal',{})
    conc=causal.get('concentration','')
    story=d.get('story',{})
    name=(story.get('blind_name') or '')[:60]
    bacc=story.get('program_bacc','')
    flag='weak' if story.get('flag') else ''
    verdict=''
    agents=set()
    for c in d.get('certification',[]):
        if isinstance(c,dict):
            if c.get('test')=='reviewer-two' or \
               c.get('gate')=='reviewer-two':
                verdict=c.get('verdict','')
            a=c.get('agent') or c.get('source')
            if a: agents.add(str(a))
    prov=d.get('provenance',{})
    if prov.get('agent'): agents.add(prov['agent'])
    return {'tag':tag,'tree':tree,'conc':conc,'bacc':bacc,
            'story':name,'flag':flag,'verdict':verdict,
            'agents':','.join(sorted(agents))[:40]}

def main():
    rows=[r for r in (one(f) for f in
          sorted(glob.glob(PT+'circuits/*.json')))
          if r and r['tag']!='registry']
    def key(r):
        vrank={'CONFIRM':0,'WEAKEN':1,'':2,'REFUTE':3}
        return (0 if 'diverse' in r['tree'] else 1,
                vrank.get(r['verdict'],2), r['tag'])
    rows.sort(key=key)
    nd=sum('diverse' in r['tree'] for r in rows)
    L=['# Circuit index (generated by make_circuit_index.py -- '
       'do not edit)','',
       f'{len(rows)} records: {nd} diverse-tree, {len(rows)-nd} '
       'old-tree (212-row). Reviewer verdicts per '
       'SWARM_RUNBOOK v2.','',
       '| tag | tree | conc | prog bacc | story | flag | '
       'reviewer | agents |',
       '|---|---|---|---|---|---|---|---|']
    for r in rows:
        L.append(f"| {r['tag']} | "
                 f"{'diverse' if 'diverse' in r['tree'] else 'old'}"
                 f" | {r['conc']} | {r['bacc']} | {r['story']} | "
                 f"{r['flag']} | {r['verdict']} | {r['agents']} |")
    open(PT+'CIRCUITS_INDEX.md','w').write('\n'.join(L)+'\n')
    print(f'wrote CIRCUITS_INDEX.md ({len(rows)} records, '
          f'{nd} diverse)')

if __name__=='__main__': main()
