#!/usr/bin/env python3
"""Generate an evidence-coverage matrix for task circuits and shared subroutines."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
CIRCUITS = ROOT / "circuits"
REGISTRY = CIRCUITS / "registry.json"
OUT_JSON = CIRCUITS / "coverage.json"
OUT_MD = ROOT / "CIRCUIT_COVERAGE.md"

CATEGORIES = {
    "capability": {"capability"},
    "causal_site": {"full_swap_ceiling"},
    "learned_interchange": {"das_interchange"},
    "cross_family": {"cross_family_transfer"},
    "ood": {"ood"},
    "selectivity": {"invariance", "removal", "null_control"},
    "composition": {"composition"},
    "compiled_weights": {"compiled_equivalence"},
}
BLOCKING = {"failed", "null", "invalid"}


def active_events(document: dict) -> list[dict]:
    events = document.get("evidence_events", [])
    superseded = {event.get("supersedes_event_id") for event in events if event.get("supersedes_event_id")}
    return [event for event in events if event["event_id"] not in superseded]


def category_cell(events: list[dict], test_types: set[str]) -> dict:
    relevant = [event for event in events if event["test_type"] in test_types]
    held = [event for event in relevant if event["verdict"] == "held"]
    blocking = [event for event in relevant if event["verdict"] in BLOCKING]
    planned = [event for event in relevant if event["stage"] == "preregistered"
               and event["verdict"] == "inconclusive"]
    if held and blocking:
        status = "mixed"
    elif blocking:
        status = "blocked"
    elif held:
        status = "held"
    elif planned:
        status = "planned"
    else:
        status = "missing"
    return {
        "status": status,
        "held_event_ids": [event["event_id"] for event in held],
        "blocking_event_ids": [event["event_id"] for event in blocking],
        "planned_event_ids": [event["event_id"] for event in planned],
        "latest_relevant_event_id": relevant[-1]["event_id"] if relevant else None,
    }


def main() -> None:
    compact = json.loads(REGISTRY.read_text())["circuits"]
    records = {}
    for tag, registry_row in sorted(compact.items()):
        if registry_row.get("schema_version") != 2 or registry_row.get("kind") not in {
            "behavior_circuit", "shared_subroutine",
        }:
            continue
        document = json.loads((CIRCUITS / registry_row["file"]).read_text())
        events = active_events(document)
        categories = {name: category_cell(events, types) for name, types in CATEGORIES.items()}
        records[tag] = {
            "kind": registry_row["kind"], "claim_status": registry_row["claim_status"],
            "causal_variable_id": registry_row["causal_variable_id"],
            "categories": categories,
            "n_held_categories": sum(cell["status"] in {"held", "mixed"} for cell in categories.values()),
            "n_blocked_categories": sum(cell["status"] in {"blocked", "mixed"} for cell in categories.values()),
            "n_missing_categories": sum(cell["status"] == "missing" for cell in categories.values()),
            "next_missing": next(claim for claim in document["claims"]
                                 if claim["claim_id"] == registry_row["active_claim_id"])["next_missing"],
        }
    payload = {
        "schema": "circuit_evidence_coverage_v1",
        "status_definitions": {
            "held": "at least one active held event and no active failed/null/invalid event in this category",
            "mixed": "active held and active failed/null/invalid events coexist; read the record before acting",
            "blocked": "at least one active failed/null/invalid event and no active held event",
            "planned": "a preregistered inconclusive event exists but no completed held/blocking evidence",
            "missing": "no active event in this category",
        },
        "categories": {name: sorted(types) for name, types in CATEGORIES.items()},
        "records": records,
    }
    OUT_JSON.write_text(json.dumps(payload, indent=1) + "\n")

    labels = {"held": "held", "mixed": "mixed", "blocked": "blocked", "planned": "planned", "missing": "—"}
    lines = [
        "# Circuit evidence coverage (generated by make_circuit_coverage.py — do not edit)", "",
        "This is a navigation view, not a certificate. `mixed` means positive and negative results coexist; open the canonical JSON record before doing more work.", "",
        "| circuit | claim | capability | causal site | learned interchange | cross-family | OOD | selectivity | composition | compiled weights | exact next work |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for tag, record in records.items():
        cell = record["categories"]
        next_work = record["next_missing"].replace("|", "/")
        lines.append(
            f"| `{tag}` | {record['claim_status']} | {labels[cell['capability']['status']]} | "
            f"{labels[cell['causal_site']['status']]} | {labels[cell['learned_interchange']['status']]} | "
            f"{labels[cell['cross_family']['status']]} | {labels[cell['ood']['status']]} | "
            f"{labels[cell['selectivity']['status']]} | {labels[cell['composition']['status']]} | "
            f"{labels[cell['compiled_weights']['status']]} | {next_work} |"
        )
    lines.extend([
        "", "## Meaning of the columns", "",
        "- **Capability:** the unmodified model performs the declared behavior on the tested examples.",
        "- **Causal site:** swapping the complete candidate activation can cause the declared change.",
        "- **Learned interchange:** a learned internal representation passes a declared interchange test.",
        "- **Cross-family:** one representation transfers across independently constructed changes of the same variable.",
        "- **OOD:** the claim predicts a genuinely shifted dataset without selection or refitting.",
        "- **Selectivity:** removal/invariance/null controls show unrelated computations are preserved.",
        "- **Composition:** joint interventions establish how this circuit combines with another variable.",
        "- **Compiled weights:** an activation claim has been translated into an executable weight-level object and retested.",
    ])
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_MD.name} and {OUT_JSON.relative_to(ROOT)} for {len(records)} canonical records")


if __name__ == "__main__":
    main()

